---
http_interactions:
- request:
    method: post
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios.json
    body:
      encoding: UTF-8
      string: '{"scenario":{"scenario_id":648695}}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.14.0
      Date:
      - Thu, 28 Jan 2021 15:55:05 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      - Origin
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"da04e539407e9d5ef45afeca693ee0ed"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 80f52949-64e6-469e-b189-14dcbccaebbd
      X-Runtime:
      - '0.051204'
    body:
      encoding: ASCII-8BIT
      string: '{"id":1397817,"title":"API","area_code":"nl","start_year":2015,"end_year":2050,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/1397817","ordering":null,"display_group":null,"scaling":null,"source":null,"template":648695,"created_at":"2021-01-28T15:55:05.000Z","protected":false}'
    http_version: 
  recorded_at: Thu, 28 Jan 2021 15:55:05 GMT
recorded_with: VCR 3.0.3
