---
http_interactions:
- request:
    method: get
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios/648695
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v2.7.3
      Authorization:
      - Bearer access_j4Q9tdKBF9DNNLJc
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Tue, 23 May 2023 11:10:35 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"1620a809decf3f8004708dbe14f56f93"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d8c4a9fa-4a86-471b-ab39-b1e6eec8e96d
      X-Runtime:
      - '0.114830'
    body:
      encoding: UTF-8
      string: '{"id":648695,"created_at":"2017-03-13T19:22:35.000Z","updated_at":"2019-12-05T09:14:10.000Z","user_values":{},"end_year":2050,"keep_compatible":true,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{"title":"ETM
        Test Scenario"},"start_year":2015,"active_couplings":[],"inactive_couplings":[],"owner":null,"scaling":null,"template":null,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/648695"}'
  recorded_at: Tue, 23 May 2023 11:10:35 GMT
- request:
    method: post
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios
    body:
      encoding: UTF-8
      string: '{"scenario":{"source":"ETM","scenario_id":648695}}'
    headers:
      User-Agent:
      - Faraday v2.7.3
      Content-Type:
      - application/json
      Authorization:
      - Bearer access_j4Q9tdKBF9DNNLJc
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Tue, 23 May 2023 11:10:35 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"74066c98ee157cfba1b200adbcd04dcf"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - cb05c1df-9760-4343-93a2-42c0392e10d6
      X-Runtime:
      - '0.031559'
    body:
      encoding: UTF-8
      string: '{"id":2259130,"created_at":"2023-05-23T11:10:35.000Z","updated_at":"2023-05-23T11:10:35.000Z","user_values":{},"end_year":2050,"keep_compatible":false,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{},"start_year":2015,"active_couplings":[],"inactive_couplings":[],"owner":null,"scaling":null,"template":648695,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/2259130"}'
  recorded_at: Tue, 23 May 2023 11:10:35 GMT
recorded_with: VCR 6.0.0
