---
- id: 1
  key: households
  section: demand
  percentage_bar_query: share_of_households_in_final_demand
  tab_key: demand
  position: 1
  parent_id:
  dependent_on: ''
- id: 2
  key: buildings
  section: demand
  percentage_bar_query: share_of_buildings_in_final_demand
  tab_key: demand
  position: 2
  parent_id:
  dependent_on: has_buildings
- id: 3
  key: transport
  section: demand
  percentage_bar_query: share_of_transport_in_final_demand
  tab_key: demand
  position: 3
  parent_id:
  dependent_on: ''
- id: 4
  key: industry
  section: demand
  percentage_bar_query: share_of_industry_and_energy_in_final_demand
  tab_key: demand
  position: 4
  parent_id:
  dependent_on: has_industry
- id: 5
  key: agriculture
  section: demand
  percentage_bar_query: share_of_agriculture_in_final_demand
  tab_key: demand
  position: 5
  parent_id:
  dependent_on: has_agriculture
- id: 6
  key: other
  section: demand
  percentage_bar_query: share_of_other_in_final_demand
  tab_key: demand
  position: 6
  parent_id:
  dependent_on: has_other
- id: 12
  key: combustion
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 4
  parent_id:
  dependent_on: ''
- id: 13
  key: nuclear
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 4
  parent_id:
  dependent_on: ''
- id: 14
  key: wind
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 5
  parent_id:
  dependent_on: ''
- id: 15
  key: water
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 6
  parent_id:
  dependent_on: ''
- id: 16
  key: solar
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 7
  parent_id:
  dependent_on: ''
- id: 18
  key: co2
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 9
  parent_id:
  dependent_on: ''
- id: 19
  key: sustainability
  section: targets
  percentage_bar_query: ''
  tab_key: targets
  position: 1
  parent_id:
  dependent_on: _always_hidden
- id: 20
  key: dependence
  section: targets
  percentage_bar_query: ''
  tab_key: targets
  position: 2
  parent_id:
  dependent_on: _always_hidden
- id: 21
  key: cost
  section: targets
  percentage_bar_query: ''
  tab_key: targets
  position: 3
  parent_id:
  dependent_on: _always_hidden
- id: 22
  key: electricity
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 1
  parent_id:
  dependent_on: ''
- id: 23
  key: electricity_renewable
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 2
  parent_id:
  dependent_on: ''
- id: 24
  key: heat
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 3
  parent_id:
  dependent_on: ''
- id: 25
  key: renewable_heat
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 4
  parent_id:
  dependent_on: _always_hidden
- id: 26
  key: transport_fuels
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 7
  parent_id:
  dependent_on: ''
- id: 28
  key: infrastructure
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 8
  parent_id:
  dependent_on: use_network_calculations
- id: 29
  key: area
  section: overview
  percentage_bar_query: ''
  tab_key: targets
  position: 4
  parent_id:
  dependent_on: _always_hidden
- id: 32
  key: fce
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 9
  parent_id:
  dependent_on: _always_hidden
- id: 33
  key: security_of_supply
  section: flexibility
  percentage_bar_query: ''
  tab_key: flexibility
  position: 10
  parent_id:
  dependent_on: ''
- id: 34
  key: merit_order
  section: flexibility
  percentage_bar_query: ''
  tab_key: costs
  position: 1
  parent_id:
  dependent_on: has_merit_order
- id: 35
  key: employment
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 11
  parent_id:
  dependent_on: _always_hidden
- id: 36
  key: costs_heat
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 3
  parent_id:
  dependent_on: ''
- id: 37
  key: fuel_costs
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 1
  parent_id:
  dependent_on: ''
- id: 38
  key: industry_metal
  section: demand
  percentage_bar_query: ''
  tab_key: demand
  position: 2
  parent_id: 4
  dependent_on: _always_hidden
- id: 39
  key: excess_electricity
  section: flexibility
  percentage_bar_query: ''
  tab_key: flexibility
  position: 2
  parent_id:
  dependent_on: has_electricity_storage
- id: 40
  key: electricity_import_export
  section: flexibility
  percentage_bar_query: ''
  tab_key: flexibility
  position: 4
  parent_id:
  dependent_on: is_national_scenario
- id: 41
  key: industry_chemical
  section: demand
  percentage_bar_query: ''
  tab_key: demand
  position: 1
  parent_id: 4
  dependent_on: _always_hidden
- id: 42
  key: industry_other
  section: demand
  percentage_bar_query: ''
  tab_key: demand
  position: 3
  parent_id: 4
  dependent_on: _always_hidden
- id: 43
  key: fuel_production
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 11
  parent_id:
  dependent_on: is_national_scenario
- id: 44
  key: costs_flexibility
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 7
  parent_id:
  dependent_on: ''
- id: 45
  key: hydrogen
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 5
  parent_id:
  dependent_on: ''
- id: 46
  key: transport_costs
  section: costs
  percentage_bar_query: ''
  tab_key: costs
  position: 4
  parent_id:
  dependent_on: ''
- id: 47
  key: biomass
  section: supply
  percentage_bar_query: ''
  tab_key: supply
  position: 8
  parent_id:
  dependent_on: ''
- id: 48
  key: data_export
  section: data
  percentage_bar_query: ''
  tab_key: data
  position: 2
  parent_id:
  dependent_on: ''
- id: 50
  key: transport_international_transport
  section: ''
  percentage_bar_query: ''
  tab_key: demand
  position: 3
  parent_id: 3
  dependent_on: ''
- id: 51
  key: transport_passenger_transport
  section: ''
  percentage_bar_query: ''
  tab_key: demand
  position: 1
  parent_id: 3
  dependent_on: ''
- id: 52
  key: transport_freight_transport
  section: ''
  percentage_bar_query: ''
  tab_key: demand
  position: 2
  parent_id: 3
  dependent_on: ''
- id: 53
  key: flexibility_storage
  section: ''
  percentage_bar_query: ''
  tab_key: flexibility
  position: 1
  parent_id: 39
  dependent_on: ''
- id: 54
  key: flexibility_conversion
  section: ''
  percentage_bar_query: ''
  tab_key: flexibility
  position: 2
  parent_id: 39
  dependent_on: ''
- id: 55
  key: flexibility_net_load
  section: ''
  percentage_bar_query: ''
  tab_key: flexibility
  position: 3
  parent_id:
  dependent_on: ''
- id: 56
  key: electricity_import_costs
  section: ''
  percentage_bar_query: ''
  tab_key: costs
  position: 5
  parent_id:
  dependent_on: ''
- id: 57
  key: data_visuals
  section: data
  percentage_bar_query: ''
  tab_key: data
  position: 1
  parent_id:
  dependent_on: ''
- id: 58
  key: costs_hydrogen
  section: ''
  percentage_bar_query: ''
  tab_key: costs
  position: 5
  parent_id:
  dependent_on: ''
- id: 59
  key: introduction
  section: ''
  percentage_bar_query: ''
  tab_key: overview
  position: 1
  parent_id:
  dependent_on: ''
- id: 60
  key: flexibility_weather
  section: ''
  percentage_bar_query: ''
  tab_key: flexibility
  position: 4
  parent_id:
  dependent_on: ''
- id: 61
  key: wacc
  section: ''
  percentage_bar_query: ''
  tab_key: costs
  position: 16
  parent_id:
  dependent_on: ''
- id: 62
  key: heat_merit
  section: ''
  percentage_bar_query: ''
  tab_key: supply
  position: 1
  parent_id: 24
  dependent_on: ''
