---
- key: households
  section: demand
  percentage_bar_query: share_of_households_in_final_demand
  tab_key: demand
  position: 1
- key: households_heating_order
  tab_key: demand
  position: 1
  parent_key: households
- key: buildings
  section: demand
  percentage_bar_query: share_of_buildings_in_final_demand
  tab_key: demand
  position: 2
- key: transport
  section: demand
  percentage_bar_query: share_of_transport_in_final_demand
  tab_key: demand
  position: 3
- key: transport_international_transport
  tab_key: demand
  position: 3
  parent_key: transport
- key: transport_passenger_transport
  tab_key: demand
  position: 1
  parent_key: transport
- key: transport_freight_transport
  tab_key: demand
  position: 2
  parent_key: transport
- key: transport_fuels
  tab_key: demand
  position: 4
  parent_key: transport
- key: industry
  section: demand
  percentage_bar_query: share_of_industry_and_energy_in_final_demand
  tab_key: demand
  position: 4
  dependent_on: has_industry
- key: agriculture
  section: demand
  percentage_bar_query: share_of_agriculture_in_final_demand
  tab_key: demand
  position: 5
  dependent_on:
- key: other
  section: demand
  percentage_bar_query: share_of_other_in_final_demand
  tab_key: demand
  position: 6
- key: export_energy
  section: demand
  tab_key: demand
  position: 7
  dependent_on:
- key: specs_electricity
  section: costs
  tab_key: costs
  position: 1
- key: specs_renewable_electricity
  section: costs
  tab_key: costs
  position: 2
- key: infrastructure
  section: costs
  tab_key: costs
  position: 3
- key: costs_heat
  section: costs
  tab_key: costs
  position: 4
- key: costs_hydrogen
  tab_key: costs
  position: 5
- key: costs_fuel_production
  section: costs
  tab_key: costs
  position: 6
- key: specs_transport
  section: costs
  tab_key: costs
  position: 7
- key: fuel_costs
  section: costs
  tab_key: costs
  position: 8
- key: costs_flexibility
  section: costs
  tab_key: costs
  position: 9
- key: co2
  section: costs
  tab_key: costs
  position: 10
- key: wacc
  tab_key: costs
  position: 11
- key: electricity
  section: supply
  tab_key: supply
  position: 1
- key: electricity_renewable
  section: supply
  tab_key: supply
  position: 2
- key: merit_order
  section: supply
  tab_key: supply
  position: 3
  dependent_on: has_merit_order
- key: heat
  section: supply
  tab_key: supply
  position: 4
- key: hydrogen
  section: supply
  tab_key: supply
  position: 5
- key: fuel_production
  section: supply
  tab_key: supply
  position: 6
- key: biomass
  section: supply
  tab_key: supply
  position: 8
- key: fuel_extraction
  section: supply
  tab_key: supply
  position: 11
- key: security_of_supply
  section: flexibility
  tab_key: flexibility
  position: 10
- key: flexibility_overview
  section: flexibility
  tab_key: flexibility
  position: 1
- key: electricity_import_export
  section: flexibility
  tab_key: flexibility
  position: 4
- key: data_export
  section: data
  tab_key: data
  position: 3
- key: data_sources
  section: data
  tab_key: data
  position: 2
- key: flexibility_storage
  tab_key: flexibility
  position: 1
- key: flexibility_forecast_storage_order
  tab_key: flexibility
  position: 1
  parent_key: flexibility_storage
- key: flexibility_conversion
  tab_key: flexibility
  position: 2
- key: flexibility_net_load
  tab_key: flexibility
  position: 3
- key: data_visuals
  section: data
  tab_key: data
  position: 1
- key: scenario_overview
  tab_key: overview
  position: 1
- key: flexibility_weather
  tab_key: flexibility
  position: 4
- key: heat_lt
  tab_key: supply
  position: 3
  parent_key: heat
- key: heat_mt
  tab_key: supply
  position: 2
  parent_key: heat
- key: heat_ht
  tab_key: supply
  position: 1
  parent_key: heat
- key: curve_upload
  section: flexibility
  tab_key: flexibility
  position: 10
- key: other_emissions
  section: emissions
  tab_key: emissions
  position: 1
- key: ccus
  section: emissions
  tab_key: emissions
  position: 2
- key: emission_factors
  section: emissions
  tab_key: emissions
  position: 3
