---
http_interactions:
- request:
    method: post
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios
    body:
      encoding: UTF-8
      string: '{"scenario":{"source":"ETM","area_code":"nl","end_year":2050}}'
    headers:
      User-Agent:
      - Faraday v2.7.3
      Content-Type:
      - application/json
      Authorization:
      - Bearer access_SQu9G7LYxXJ3S9Hv
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Mon, 15 May 2023 10:08:09 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"843119c652d87c91656da4bbb3159beb"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - e4ab2486-b136-4297-a2de-a9b1d560c7a3
      X-Runtime:
      - '1.736149'
    body:
      encoding: UTF-8
      string: '{"id":2255690,"created_at":"2023-05-15T10:08:09.000Z","updated_at":"2023-05-15T10:08:09.000Z","user_values":{},"end_year":2050,"keep_compatible":false,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{},"start_year":2015,"owner":null,"active_couplings":[],"inactive_couplings":[],"scaling":null,"template":null,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/2255690"}'
  recorded_at: Mon, 15 May 2023 10:08:09 GMT
- request:
    method: get
    uri: http://localhost:3002/api/v1/versions.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"b333f2b38e283af4a4b94a9463c73f73"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - ba145ef1-eb8c-4878-a566-ef1a490320ad
      X-Runtime:
      - '0.006664'
      Server-Timing:
      - start_processing.action_controller;dur=0.00, sql.active_record;dur=0.28, instantiation.active_record;dur=0.02,
        process_action.action_controller;dur=0.79
      Vary:
      - Origin
      Content-Length:
      - '416'
    body:
      encoding: UTF-8
      string: '{"versions":[{"tag":"latest","model_url":"http://localhost:3001","engine_url":"http://localhost:3000","collections_url":"http://localhost:3005"},{"tag":"stable.01","model_url":"http://localhost:3001","engine_url":"http://localhost:3000","collections_url":"http://localhost:3005"},{"tag":"stable.02","model_url":"http://localhost:3001","engine_url":"http://localhost:3000","collections_url":"http://localhost:3005"}]}'
  recorded_at: Fri, 24 Jan 2025 13:06:39 GMT
recorded_with: VCR 6.0.0
