---
- label: heat
  color: "#E84118"
  order_by: 1
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heat_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: heat_breakdown_of_total_cost_per_household
- label: electricity
  color: "#0984E3"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: electricity_breakdown_of_total_cost_per_household
- label: fuels
  color: "#6AB04C"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: fuels_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: fuels_breakdown_of_total_cost_per_household
- label: non_energetic_fuels
  color: "#006266"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: non_energetic_fuels_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: non_energetic_fuels_breakdown_of_total_cost_per_household
- label: network
  color: "#F9CA24"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: network_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: network_breakdown_of_total_cost_per_household
- label: vehicles
  color: "#FFA500"
  order_by: 6
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: vehicles_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: vehicles_breakdown_of_total_cost_per_household
- label: hydrogen
  color: "#87CEEB"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: hydrogen_breakdown_of_total_cost_per_household
- label: flexibility
  color: "#786FA6"
  order_by: 8
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: flexibility_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: flexibility_breakdown_of_total_cost_per_household
- label: ccus
  color: "#000000"
  order_by: 9
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ccus_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: ccus_breakdown_of_total_costs_per_household
- label: insulation
  color: "#8B0000"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: insulation_in_breakdown_of_total_costs_per_household
  is_1990: false
  dependent_on:
  output_element_key: breakdown_of_total_cost_per_household
  key: insulation_breakdown_of_total_costs_per_household
