---
- label: demand
  color: "#FF0000"
  order_by: 1
  group: 
  show_at_first: 
  is_target_line: true
  target_line_position: 
  gquery: hourly_buildings_heat_demand
  is_1990: 
  dependent_on: 
  output_element_key: buildings_heat_demand_and_production
  key: demand_buildings_heat_demand_and_production
- label: production
  color: "#648FFF"
  order_by: 2
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: hourly_buildings_heat_production
  is_1990: 
  dependent_on: 
  output_element_key: buildings_heat_demand_and_production
  key: production_buildings_heat_demand_and_production
