---
- label: other_final_demand_steam_hot_water_in_collective_heat_network_mekko
  color: "#786FA6"
  order_by: 5
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: other_final_demand_steam_hot_water_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: other_final_demand_steam_hot_water_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_heat_unused_steam_hot_water_in_collective_heat_network_mekko
  color: "#FF8C8C"
  order_by: 1
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_unused_steam_hot_water_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_unused_steam_hot_water_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_heat_well_geothermal_in_collective_heat_network_mekko
  color: "#FFA502"
  order_by: 7
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_well_geothermal_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_well_geothermal_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: households_final_demand_steam_hot_water_in_collective_heat_network_mekko
  color: "#E69567"
  order_by: 2
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: households_final_demand_steam_hot_water_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: households_final_demand_steam_hot_water_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_heat_burner_wood_pellets_in_collective_heat_network_mekko
  color: "#009432"
  order_by: 8
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_wood_pellets_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_burner_wood_pellets_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_distribution_loss_in_collective_heat_network_mekko
  color: "#800080"
  order_by: 6
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_distribution_loss_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_distribution_loss_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_direct_air_capture_in_collective_heat_network_mekko
  color: "#b71540"
  order_by: 7
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_direct_air_capture_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_direct_air_capture_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_heat_heatpump_water_water_electricity_in_collective_heat_network_mekko
  color: "#ADD8E6"
  order_by: 9
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_heatpump_water_water_electricity_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_heatpump_water_water_electricity_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_boiler_electricity_in_collective_heat_network_mekko
  color: "#b9effe"
  order_by: 13
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_boiler_electricity_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_boiler_electricity_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_import_steam_hot_water_in_collective_heat_network_mekko
  color: "#e61919"
  order_by: 10
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_import_steam_hot_water_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_import_steam_hot_water_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_solar_thermal_in_collective_heat_network_mekko
  color: "#FFD700"
  order_by: 11
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_solar_thermal_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_solar_thermal_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_backup_burner_network_gas_in_collective_heat_network_mekko
  color: "#CED6E0"
  order_by: 12
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_backup_burner_network_gas_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_backup_burner_network_gas_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_burner_crude_oil_in_collective_heat_network_mekko
  color: "#CD6133"
  order_by: 14
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_crude_oil_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_burner_crude_oil_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_burner_hydrogen_in_collective_heat_network_mekko
  color: "#87CEEB"
  order_by: 15
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_hydrogen_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_burner_hydrogen_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_burner_network_gas_in_collective_heat_network_mekko
  color: "#A4B0BE"
  order_by: 16
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_network_gas_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_burner_network_gas_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_burner_waste_mix_in_collective_heat_network_mekko
  color: "#006266"
  order_by: 17
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_waste_mix_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_burner_waste_mix_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chp_supercritical_waste_mix_in_collective_heat_network_mekko
  color: "#218C74"
  order_by: 18
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_supercritical_waste_mix_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_supercritical_waste_mix_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chp_ultra_supercritical_lignite_in_collective_heat_network_mekko
  color: "#222F3E"
  order_by: 19
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_ultra_supercritical_lignite_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_ultra_supercritical_lignite_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chps_coal_in_collective_heat_network_mekko
  color: "#485460"
  order_by: 20
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chps_coal_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chps_coal_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chp_local_engine_network_gas_in_collective_heat_network_mekko
  color: "#DFE4EA"
  order_by: 21
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_local_engine_network_gas_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_local_engine_network_gas_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chp_local_wood_pellets_in_collective_heat_network_mekko
  color: "#3D6B0D"
  order_by: 22
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_local_wood_pellets_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_local_wood_pellets_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: buildings_final_demand_steam_hot_water_in_collective_heat_network_mekko
  color: "#F9CA24"
  order_by: 3
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: buildings_final_demand_steam_hot_water_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: buildings_final_demand_steam_hot_water_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_chp_combined_cycle_network_gas_in_collective_heat_network_mekko
  color: "#A4B0BE"
  order_by: 22
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_combined_cycle_network_gas_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_combined_cycle_network_gas_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chp_local_engine_biogas_in_collective_heat_network_mekko
  color: "#CE8814"
  order_by: 23
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_local_engine_biogas_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_local_engine_biogas_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: agriculture_final_demand_steam_hot_water_in_collective_heat_network_mekko
  color: "#6AB04C"
  order_by: 4
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: agriculture_final_demand_central_steam_hot_water_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: agriculture_final_demand_central_steam_hot_water_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_heat_burner_coal_in_collective_heat_network_mekko
  color: "#333333"
  order_by: 24
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_coal_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_burner_coal_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_network_storage_loss_in_collective_heat_network_mekko
  color: "#FBCCD1"
  order_by: 1
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_network_storage_loss_in_collective_heat_network_mekko
  is_1990: false
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_network_storage_loss_in_collective_heat_network_mekko_demand_collective_heat_mekko
- label: energy_heat_industry_residual_heat_in_collective_heat_network_mekko
  color: "#00008B"
  order_by: 5
  group: supply
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: energy_heat_industry_residual_heat_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_industry_residual_heat_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_flexibility_p2h_boiler_electricity_in_collective_heat_network_mekko
  color: "#46c1e3"
  order_by: 25
  group: supply
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: energy_heat_flexibility_p2h_boiler_electricity_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_flexibility_p2h_boiler_electricity_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_heat_flexibility_p2h_heatpump_electricity_in_collective_heat_network_mekko
  color: "blue"
  order_by: 26
  group: supply
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: energy_heat_flexibility_p2h_heatpump_electricity_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_heat_flexibility_p2h_heatpump_electricity_in_collective_heat_network_mekko_supply_collective_heat_mekko
- label: energy_chp_supercritical_ccs_waste_mix_in_collective_heat_network_mekko
  color: "#16a085"
  order_by: 27
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_supercritical_ccs_waste_mix_in_collective_heat_network_mekko
  is_1990:
  dependent_on:
  output_element_key: collective_heat_mekko
  key: energy_chp_supercritical_ccs_waste_mix_in_collective_heat_network_mekko_supply_collective_heat_mekko
