---
- label: costs_building_and_installations_households
  color: "#002B42"
  order_by: 100
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_households
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_households_costs_overview_detailed
- label: costs_building_and_installations_buildings
  color: "#194054"
  order_by: 110
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_buildings
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_buildings_costs_overview_detailed
- label: costs_building_and_installations_agriculture
  color: "#325567"
  order_by: 120
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_agriculture
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_agriculture_costs_overview_detailed
- label: costs_building_and_installations_industry
  color: "#667f8d"
  order_by: 140
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_industry
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_industry_costs_overview_detailed

- label: costs_carriers_biomass
  color: "#619ab7"
  order_by: 200
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_biomass
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_biomass_costs_overview_detailed
- label: costs_carriers_coal_and_products
  color: "#70a4be"
  order_by: 210
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_coal_and_products
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_coal_and_products_costs_overview_detailed
- label: costs_carriers_electricity
  color: "#80aec5"
  order_by: 220
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_electricity
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_electricity_costs_overview_detailed
- label: costs_carriers_heat
  color: "#90b8cc"
  order_by: 230
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_heat
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_heat_costs_overview_detailed
- label: costs_carriers_hydrogen_carriers
  color: "#a0c2d3"
  order_by: 240
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_hydrogen_carriers
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_hydrogen_carriers_costs_overview_detailed
- label: costs_carriers_natural_gas
  color: "#b0ccdb"
  order_by: 250
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_natural_gas
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_natural_gas_costs_overview_detailed
- label: costs_carriers_oil_and_products
  color: "#bfd6e2"
  order_by: 260
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_oil_and_products
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_oil_and_products_costs_overview_detailed
- label: costs_carriers_uranium
  color: "#cfe0e9"
  order_by: 270
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_uranium
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_uranium_costs_overview_detailed
- label: costs_carriers_waste
  color: "#dfeaf0"
  order_by: 280
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_waste
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_waste_costs_overview_detailed
- label: costs_carriers_ammonia
  color: "#ebf3f7"
  order_by: 290
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_ammonia
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_ammonia_costs_overview_detailed

- label: costs_production_biomass
  color: "#C5D75F"
  order_by: 300
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_biomass
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_biomass_costs_overview_detailed
- label: costs_production_chp_plants
  color: "#cadb6f"
  order_by: 310
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_chp_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_chp_plants_overview_detailed
- label: costs_production_dedicated_hydrogen_production
  color: "#D0DF7E"
  order_by: 320
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_dedicated_hydrogen_production
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_dedicated_hydrogen_production_costs_overview_detailed
- label: costs_production_heat_plants
  color: "#D6E38F"
  order_by: 330
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_heat_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_heat_plants_costs_overview_detailed
- label: costs_production_other
  color: "#DCE79F"
  order_by: 340
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_other
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_other_costs_overview_detailed
- label: costs_production_power_plants
  color: "#E2EBAF"
  order_by: 350
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_power_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_power_plants_costs_overview_detailed

- label: costs_storage_and_conversion_p2p
  color: "#CAB39E"
  order_by: 400
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2p
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2p_costs_overview_detailed
- label: costs_storage_and_conversion_p2g
  color: "#cfbaa7"
  order_by: 410
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2g
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2g_costs_overview_detailed
- label: costs_storage_and_conversion_p2h
  color: "#d4c2b1"
  order_by: 420
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2h
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2h_costs_overview_detailed
- label: costs_storage_and_conversion_storage
  color: "#d9c9bb"
  order_by: 430
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_storage
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_storage_costs_overview_detailed

- label: costs_infrastructure_electricity
  color: "#702283"
  order_by: 500
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_electricity
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_electricity_costs_overview_detailed
- label: costs_infrastructure_heat
  color: "#7e388f"
  order_by: 510
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_heat
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_heat_costs_overview_detailed
- label: costs_infrastructure_hydrogen
  color: "#8c4e9b"
  order_by: 520
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_hydrogen
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_hydrogen_costs_overview_detailed
- label: costs_infrastructure_network_gas
  color: "#9a64a8"
  order_by: 530
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_network_gas
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_network_gas_costs_overview_detailed
- label: costs_infrastructure_ammonia
  color: "#C586D6"
  order_by: 540
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_ammonia
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_ammonia_costs_overview_detailed
- label: costs_infrastructure_diesel
  color: "#EDA9FF"
  order_by: 550
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_diesel
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_diesel_costs_overview_detailed
- label: costs_infrastructure_liquid_hydrogen
  color: "#C6ABCE"
  order_by: 560
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_liquid_hydrogen
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_liquid_hydrogen_costs_overview_detailed
- label: costs_infrastructure_lng
  color: "#EAC8F5"
  order_by: 570
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_lng
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_lng_costs_overview_detailed
- label: costs_infrastructure_lohc
  color: "#EED2F7"
  order_by: 580
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_lohc
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_lohc_costs_overview_detailed

- label: costs_co2_ccus
  unit: euro
  color: "#fc653d"
  order_by: 600
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2_ccus
  is_1990:
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_co2_ccus_costs_overview_detailed
- label: costs_co2_emissions_costs
  unit: euro
  color: "#FCC43D"
  order_by: 650
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2_energy_graph_co2_emissions_costs
  is_1990:
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_co2_emissions_costs_costs_overview_detailed
- label: costs_captured_biogenic_emissions
  unit: euro
  color: "#fde7b1"
  order_by: 700
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2_energy_graph_co2_captured_biogenic_costs
  is_1990:
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_captured_biogenic_emissions_costs_overview_detailed  
