---
- label: baseload_demand
  color: "#CC0000"
  order_by: 1
  group:
  show_at_first:
  is_target_line: true
  target_line_position:
  gquery: total_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: total_demand_dynamic_demand_curve
- label: merit_households_other
  color: "#E84118"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_households_other_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_households_other_dynamic_demand_curve
- label: merit_households_space_heating
  color: "#FF6B6B"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_households_space_heating_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_households_space_heating_dynamic_demand_curve
- label: merit_households_hot_water
  color: "#FF0000"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_households_hot_water_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_households_hot_water_dynamic_demand_curve
- label: merit_buildings_space_heating
  color: "#F6E58D"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_buildings_space_heating_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_buildings_space_heating_dynamic_demand_curve
- label: merit_buildings_other
  color: "#F9CA24"
  order_by: 6
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_buildings_other_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_buildings_other_dynamic_demand_curve
- label: merit_ev_demand
  color: "#0984E3"
  order_by: 7
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_ev_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_ev_demand_dynamic_demand_curve
- label: merit_transport_other
  color: "#74B9FF"
  order_by: 8
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_transport_other_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_transport_other_dynamic_demand_curve
- label: merit_collective_heat
  color: "#8B0000"
  order_by: 9
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: mv_energy_heat_load_curve
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_collective_heat_dynamic_demand_curve
- label: merit_agriculture
  color: "#6AB04C"
  order_by: 10
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_agriculture_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_agriculture_dynamic_demand_curve
- label: other
  color: "#FFA502"
  order_by: 11
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_other_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: other_dynamic_demand_curve
- label: losses_in_storage
  color: "#D87093"
  order_by: 12
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_hv_network_loss
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: losses_in_storage_dynamic_demand_curve
- label: merit_industry_metals
  color: "#666666"
  order_by: 13
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_industry_metals_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_industry_metals_dynamic_demand_curve
- label: merit_industry_chemical
  color: "#2F3640"
  order_by: 14
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_industry_chemical_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_industry_chemical_dynamic_demand_curve
- label: merit_industry_other
  color: "#353B48"
  order_by: 15
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_industry_other_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_industry_other_dynamic_demand_curve
- label: merit_industry_transformation
  color: "#9A9C9C"
  order_by: 18
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_industry_transformation_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_industry_transformation_dynamic_demand_curve
- label: flexibility_conversion_and_storage
  color: "#0AA1DD"
  order_by: 20
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: merit_other_flexibility_demand
  is_1990:
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: flexibility_dynamic_demand_curve
- label: flexibility_export
  color: "#79DAE8"
  order_by: 21
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_energy_export_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_export_dynamic_demand_curve
- label: flexibility_curtailment
  color: "#E8F9FD"
  order_by: 22
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: merit_flexibility_curtailment_demand
  is_1990: false
  dependent_on:
  output_element_key: dynamic_demand_curve
  key: merit_flexibility_curtailment_demand_dynamic_demand_curve

