---
- label: capex
  color: "#ffb300"
  order_by: 100
  group: power_to_gas
  is_target_line: false
  gquery: integral_fixed_cost_power_to_gas
  output_element_key: flexibility_integral_costs
  key: integral_fixed_cost_power_to_gas_flexibility_integral_costs
- label: opex
  color: "#e07033"
  order_by: 105
  group: power_to_gas
  is_target_line: false
  gquery: integral_variable_cost_power_to_gas
  output_element_key: flexibility_integral_costs
  key: integral_variable_cost_power_to_gas_flexibility_integral_costs
- label: electricity_cost
  color: "#4169e1"
  order_by: 110
  group: power_to_gas
  is_target_line: false
  gquery: integral_electricity_cost_power_to_gas
  output_element_key: flexibility_integral_costs
  key: integral_electricity_cost_power_to_gas_flexibility_integral_costs
- label: hydrogen_price
  color: "red"
  order_by: 115
  group: power_to_gas
  is_target_line: true
  gquery: integral_reference_price_power_to_gas
  output_element_key: flexibility_integral_costs
  key: integral_reference_price_power_to_gas_flexibility_integral_costs

- label: capex
  color: "#ffb300"
  order_by: 150
  group: power_to_gas_offshore
  is_target_line: false
  gquery: integral_fixed_cost_power_to_gas
  output_element_key: flexibility_integral_costs
  key: integral_fixed_cost_power_to_gas_offshore_flexibility_integral_costs
- label: opex
  color: "#e07033"
  order_by: 160
  group: power_to_gas_offshore
  is_target_line: false
  gquery: integral_variable_cost_power_to_gas_offshore
  output_element_key: flexibility_integral_costs
  key: integral_variable_cost_power_to_gas_offshore_flexibility_integral_costs
- label: electricity_cost
  color: "#4169e1"
  order_by: 170
  group: power_to_gas_offshore
  is_target_line: false
  gquery: integral_electricity_cost_power_to_gas_offshore
  output_element_key: flexibility_integral_costs
  key: integral_electricity_cost_power_to_gas_offshore_flexibility_integral_costs
- label: hydrogen_price
  color: "red"
  order_by: 180
  group: power_to_gas_offshore
  is_target_line: true
  gquery: integral_reference_price_power_to_gas
  output_element_key: flexibility_integral_costs
  key: integral_reference_price_power_to_gas_offshore_flexibility_integral_costs

- label: capex
  color: "#ffb300"
  order_by: 200
  group: power_to_heat_network
  is_target_line: false
  gquery: integral_fixed_cost_power_to_heat_network
  output_element_key: flexibility_integral_costs
  key: integral_fixed_cost_power_to_heat_network_flexibility_integral_costs
- label: opex
  color: "#e07033"
  order_by: 205
  group: power_to_heat_network
  is_target_line: false
  gquery: integral_variable_cost_power_to_heat_network
  output_element_key: flexibility_integral_costs
  key: integral_variable_cost_power_to_heat_network_flexibility_integral_costs
- label: electricity_cost
  color: "#4169e1"
  order_by: 210
  group: power_to_heat_network
  is_target_line: false
  gquery: integral_electricity_cost_power_to_heat_network
  output_element_key: flexibility_integral_costs
  key: integral_electricity_cost_power_to_heat_network_flexibility_integral_costs

- label: capex
  color: "#ffb300"
  order_by: 300
  group: power_to_heat_industry
  is_target_line: false
  gquery: integral_fixed_cost_power_to_heat_industry
  output_element_key: flexibility_integral_costs
  key: integral_fixed_cost_power_to_heat_industry_flexibility_integral_costs
- label: opex
  color: "#e07033"
  order_by: 305
  group: power_to_heat_industry
  is_target_line: false
  gquery: integral_variable_cost_power_to_heat_industry
  output_element_key: flexibility_integral_costs
  key: integral_variable_cost_power_to_heat_industry_flexibility_integral_costs
- label: electricity_cost
  color: "#4169e1"
  order_by: 310
  group: power_to_heat_industry
  is_target_line: false
  gquery: integral_electricity_cost_power_to_heat_industry
  output_element_key: flexibility_integral_costs
  key: integral_electricity_cost_power_to_heat_industry_flexibility_integral_costs

- label: capex
  color: "#ffb300"
  order_by: 400
  group: power_to_heat_agriculture
  is_target_line: false
  gquery: integral_fixed_cost_power_to_heat_agriculture
  output_element_key: flexibility_integral_costs
  key: integral_fixed_cost_power_to_heat_agriculture_flexibility_integral_costs
- label: opex
  color: "#e07033"
  order_by: 405
  group: power_to_heat_agriculture
  is_target_line: false
  gquery: integral_variable_cost_power_to_heat_agriculture
  output_element_key: flexibility_integral_costs
  key: integral_variable_cost_power_to_heat_agriculture_flexibility_integral_costs
- label: electricity_cost
  color: "#4169e1"
  order_by: 410
  group: power_to_heat_agriculture
  is_target_line: false
  gquery: integral_electricity_cost_power_to_heat_agriculture
  output_element_key: flexibility_integral_costs
  key: integral_electricity_cost_power_to_heat_agriculture_flexibility_integral_costs

- label: capex
  color: "#ffb300"
  order_by: 500
  group: power_to_power
  is_target_line: false
  gquery: integral_fixed_cost_power_to_power
  output_element_key: flexibility_integral_costs
  key: integral_fixed_cost_power_to_power_flexibility_integral_costs
- label: opex
  color: "#e07033"
  order_by: 505
  group: power_to_power
  is_target_line: false
  gquery: integral_variable_cost_power_to_power
  output_element_key: flexibility_integral_costs
  key: integral_variable_cost_power_to_power_flexibility_integral_costs
- label: electricity_cost
  color: "#4169e1"
  order_by: 510
  group: power_to_power
  is_target_line: false
  gquery: integral_electricity_cost_power_to_power
  output_element_key: flexibility_integral_costs
  key: integral_electricity_cost_power_to_power_flexibility_integral_costs
- label: electricity_revenue
  color: "blue"
  order_by: 515
  group: power_to_power
  is_target_line: true
  gquery: integral_reference_price_power_to_power
  output_element_key: flexibility_integral_costs
  key: integral_reference_price_power_to_power_flexibility_integral_costs
