---
- color: "#4169E1"
  dependent_on:
  gquery: electricity_imbalance_inflexible_curve
  key: electricity_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: electricity_total_system
  order_by: 100
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance
- color: "#062c9c"
  dependent_on:
  gquery: electricity_local_households_imbalance_inflexible_curve
  key: electricity_local_households_imbalance_inflexible_curve_flexibility_hourly_carriers_inflexible_imbalance
  label: electricity_local_households
  order_by: 100
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#B22222"
  dependent_on:
  gquery: heat_network_imbalance_inflexible_curve
  key: heat_network_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: heat
  order_by: 200
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#CCCCCC"
  dependent_on:
  gquery: network_gas_imbalance_inflexible_curve
  key: network_gas_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: gas
  order_by: 300
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#999999"
  dependent_on:
  gquery: network_gas_imbalance_inflexible_smoothed_curve
  key: network_gas_imbalance_inflexible_smoothed_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: gas_smoothed
  order_by: 305
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#87CEEB"
  dependent_on:
  gquery: hydrogen_imbalance_inflexible_curve
  key: hydrogen_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: hydrogen
  order_by: 400
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#69a2b8"
  dependent_on:
  gquery: hydrogen_imbalance_inflexible_smoothed_curve
  key: hydrogen_imbalance_inflexible_smoothed_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: hydrogen_smoothed
  order_by: 405
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance
