---
- label: coal
  color: "#333333"
  order_by: 10
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_in_future_energy_imports
  is_1990: 
  dependent_on: 
  output_element_key: future_energy_imports
  key: coal_future_future_energy_imports
- label: oil
  color: "#854321"
  order_by: 20
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: oil_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: oil_future_future_energy_imports
- label: oil_products
  color: "#854321"
  order_by: 30
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: oil_products_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: oil_products_future_future_energy_imports
- label: natural_gas
  color: "#CCCCCC"
  order_by: 40
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: gas_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
- label: uranium
  color: "#E07033"
  order_by: 50
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: uranium_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: uranium_future_future_energy_imports
  key: natural_gas_future_future_energy_imports
- label: electricity
  color: "#63A1C9"
  order_by: 60
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_in_future_energy_imports
  is_1990: 
  dependent_on: 
  output_element_key: future_energy_imports
  key: electricity_future_future_energy_imports
- label: biogenic_fuels
  color: "#5D7929"
  order_by: 70
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biomass_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: biogenic_fuels_future_future_energy_imports
- label: hydrogen
  color: "#BFEFFF"
  order_by: 80
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: hydrogen_future_future_energy_imports
- label: liquid_hydrogen
  color: "#d9f5ff"
  order_by: 80
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: liquid_hydrogen_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: liquid_hydrogen_future_future_energy_imports
- label: lohc
  color: "#f2fcff"
  order_by: 80
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lohc_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: lohc_future_future_energy_imports
- label: ammonia
  color: "#1ce6d6"
  order_by: 85
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ammonia_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: ammonia_future_future_energy_imports
- label: lng
  color: "#696969"
  order_by: 90
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lng_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: future_energy_imports
  key: lng_future_future_energy_imports
- label: imported_heat_waterfall
  color: "#E84118"
  order_by: 100
  group: future
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: imported_heat_value_in_future_energy_imports
  is_1990: 
  dependent_on: 
  output_element_key: future_energy_imports
  key: imported_heat_waterfall_future_future_energy_imports
