---
- label: heat_network_demand
  color: "#FF0000"
  order_by: 1
  group:
  show_at_first:
  is_target_line: true
  target_line_position:
  gquery: heat_network_ht_demand_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: heat_network_demand_heat_network_production_ht
- label: energy_chp_combined_cycle_network_gas_steam_hot_water_output_curve
  color: "#A4B0BE"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_chp_combined_cycle_network_gas_ht_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_combined_cycle_network_gas_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chp_local_engine_biogas_steam_hot_water_output_curve
  color: "#CE8814"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_chp_local_engine_biogas_ht_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_local_engine_biogas_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chp_local_engine_network_gas_steam_hot_water_output_curve
  color: "#DFE4EA"
  order_by: 4
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_local_engine_network_gas_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_local_engine_network_gas_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chp_local_wood_pellets_steam_hot_water_output_curve
  color: "#3D6B0D"
  order_by: 5
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_local_wood_pellets_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_local_wood_pellets_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chp_supercritical_waste_mix_steam_hot_water_output_curve
  color: "#218C74"
  order_by: 6
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_supercritical_waste_mix_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_supercritical_waste_mix_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chp_supercritical_ccs_waste_mix_steam_hot_water_output_curve
  color: "#218C74"
  order_by: 6
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_supercritical_ccs_waste_mix_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_supercritical_ccs_waste_mix_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chp_ultra_supercritical_lignite_steam_hot_water_output_curve
  color: "#222F3E"
  order_by: 7
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_ultra_supercritical_lignite_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chp_ultra_supercritical_lignite_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_chps_coal_steam_hot_water_output_curve
  color: "#485460"
  order_by: 8
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_chp_coal_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_chps_coal_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_backup_burner_network_gas_steam_hot_water_output_curve
  color: "#CED6E0"
  order_by: 19
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_backup_burner_network_gas_ht_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_backup_burner_network_gas_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_burner_crude_oil_steam_hot_water_output_curve
  color: "#CD6133"
  order_by: 10
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_crude_oil_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_burner_crude_oil_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_burner_coal_steam_hot_water_output_curve
  color: "#333333"
  order_by: 11
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_coal_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_burner_coal_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_burner_hydrogen_steam_hot_water_output_curve
  color: "#87CEEB"
  order_by: 12
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_hydrogen_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_burner_hydrogen_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_burner_network_gas_steam_hot_water_output_curve
  color: "#A4B0BE"
  order_by: 13
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_network_gas_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_burner_network_gas_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_burner_waste_mix_steam_hot_water_output_curve
  color: "#006266"
  order_by: 14
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_waste_mix_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_burner_waste_mix_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_burner_wood_pellets_steam_hot_water_output_curve
  color: "#009432"
  order_by: 15
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_wood_pellets_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_burner_wood_pellets_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_heatpump_water_water_electricity_steam_hot_water_output_curve
  color: "#ADD8E6"
  order_by: 16
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_heatpump_water_water_electricity_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_heatpump_water_water_electricity_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_boiler_electricity_steam_hot_water_output_curve
  color: "#b9effe"
  order_by: 17
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_boiler_electricity_ht_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_boiler_electricity_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_import_steam_hot_water_steam_hot_water_output_curve
  color: "#FF8C8C"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_import_steam_hot_water_ht_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_import_steam_hot_water_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_well_deep_geothermal_steam_hot_water_output_curve
  color: "#FFA502"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_well_deep_geothermal_ht_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_well_geothermal_ht_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_network_storage_out
  color: "#0984E3"
  order_by: 20
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_network_storage_ht_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_ht
  key: energy_heat_network_storage_ht_steam_hot_water_out_heat_network_production
