---
- label: hydrogen_demand
  color: "#CC0000"
  order_by: 1
  group: 
  show_at_first: 
  is_target_line: true
  target_line_position: 
  gquery: hydrogen_demand_curve
  is_1990: 
  dependent_on: 
  output_element_key: hydrogen_production
  key: hydrogen_demand_hydrogen_production
- label: energy_hydrogen_biomass_gasification_ccs
  color: "#A4B0BE"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_biomass_gasification_ccs_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_biomass_gasification_ccs_hydrogen_production
- label: energy_hydrogen_biomass_gasification
  color: "#A2D679"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_biomass_gasification_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_biomass_gasification_hydrogen_production
- label: energy_hydrogen_electrolysis_solar_electricity
  color: "#FDE97B"
  order_by: 9
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_electrolysis_solar_electricity_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_electrolysis_solar_electricity_hydrogen_production
- label: energy_hydrogen_electrolysis_wind_electricity
  color: "#63A1C9"
  order_by: 10
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_electrolysis_wind_electricity_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_electrolysis_wind_electricity_hydrogen_production
- label: energy_hydrogen_steam_methane_reformer_ccs
  color: "#DFE4EA"
  order_by: 6
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_ccs_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_steam_methane_reformer_ccs_hydrogen_production
- label: energy_hydrogen_steam_methane_reformer
  color: "#BEC3C8"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_steam_methane_reformer_hydrogen_production
- label: energy_hydrogen_autothermal_reformer_ccs
  color: "#D5C6BA"
  order_by: 7
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_autothermal_reformer_ccs_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_autothermal_reformer_ccs_hydrogen_production
- label: energy_hydrogen_autothermal_reformer
  color: "#A59990"
  order_by: 8
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_autothermal_reformer_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_autothermal_reformer_hydrogen_production
- label: hydrogen_storage_depleted_gas_field
  color: "#87CEEB"
  order_by: 11
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_storage_depleted_gas_field_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: hydrogen_storage_depleted_gas_fiel_dhydrogen_production
- label: hydrogen_storage_salt_cavern
  color: "#5e9aa4"
  order_by: 12
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_storage_salt_cavern_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: hydrogen_storage_salt_cavern_hydrogen_production
- label: imported_hydrogen
  color: "#C6C2DA"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_imported_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: imported_hydrogen_hydrogen_production
- label: industry_residual_hydrogen
  color: "#006400"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_residual_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: industry_residual_hydroge_hydrogen_production
- label: energy_hydrogen_ammonia_reformer
  color: "#1ce6d6"
  order_by: 9
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_ammonia_reformer_hydrogen_output_curve
  is_1990: false
  dependent_on: 
  output_element_key: hydrogen_production
  key: energy_hydrogen_ammonia_reformer_hydrogen_production
