---
- label: households_heating_demand
  color: "#8B0000"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_houses_useful_demand_for_heating
  is_1990:
  dependent_on:
  output_element_key: impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
  key: households_heating_demand_impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
- label: households_cooling_demand
  color: "#00008B"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_houses_useful_demand_for_cooling
  is_1990:
  dependent_on:
  output_element_key: impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
  key: households_cooling_demand_impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
- label: buildings_cooling_demand
  color: "#ADD8E6"
  order_by: 1
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: buildings_useful_demand_for_cooling
  is_1990:
  dependent_on:
  output_element_key: impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
  key: buildings_cooling_demand_impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
- label: buildings_heating_demand
  color: "#FFA500"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: buildings_useful_demand_for_heating
  is_1990:
  dependent_on:
  output_element_key: impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
  key: buildings_heating_demand_impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
- label: agriculture_heating_demand
  color: "#E69567"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: agriculture_useful_demand_for_heating
  is_1990:
  dependent_on:
  output_element_key: impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
  key: agriculture_heating_demand_impact_of_climate_on_heat_and_cooling_demand_households_and_buildings
