---
- label: residual_load_excess_peak
  color: "blue"
  order_by: 100
  group: electricity
  is_target_line: true
  gquery: electricity_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_capacities
  key: excess_peak_electricity_installed_flexible_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 105
  group: electricity
  is_target_line: true
  gquery: electricity_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_capacities
  key: shortage_peak_electricity_installed_flexible_capacities

- label: electricity_interconnection_export
  color: "#77dd99"
  order_by: 120
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_export_capacity
  output_element_key: installed_flexible_capacities
  key: export_interconnection_electricity_installed_flexible_capacities
- label: power_to_heat_for_district_heating
  color: "#FFA502"
  order_by: 126
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_heat_district_heating_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_heat_for_district_heating_electricity_installed_flexible_capacities
- label: power_to_heat_for_industry
  color: "#8B0000"
  order_by: 127
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_heat_industry_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_heat_for_industry_electricity_installed_flexible_capacities
- label: power_to_heat_for_agriculture
  color: "#FFD700"
  order_by: 127
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_heat_agriculture_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_heat_for_agriculture_electricity_installed_flexible_capacities
- label: power_to_hydrogen
  color: "#dd9977"
  order_by: 128
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_hydrogen_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_hydrogen_electricity_installed_flexible_capacities
- label: electricity_storage
  color: "#dd77bb"
  order_by: 110
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_power_input_electricity_installed_flexible_capacities
- label: coal_to_power
  color: "#000000"
  order_by: 140
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_coal_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: coal_to_power_electricity_installed_flexible_capacities
- label: gas_to_power
  color: "#969696"
  order_by: 142
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_gas_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: gas_to_power_electricity_installed_flexible_capacities
- label: hydrogen_to_power
  color: "#a3def7"
  order_by: 141
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_hydrogen_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: hydrogen_to_power_electricity_installed_flexible_capacities
- label: electricity_interconnection_import
  color: "#77bbdd"
  order_by: 119
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_import_capacity
  output_element_key: installed_flexible_capacities
  key: import_interconnection_electricity_installed_flexible_capacities
- label: nuclear_to_power
  color: "#fd8d3c"
  order_by: 146
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_nuclear_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: nuclear_to_power_electricity_installed_flexible_capacities
- label: oil_to_power
  color: "#7f2704"
  order_by: 148
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_oil_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: oil_to_power_electricity_installed_flexible_capacities
- label: electricity_storage
  color: "#dd77bb"
  order_by: 112
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_power_output_electricity_installed_flexible_capacities
- label: waste_to_power
  color: "#006266"
  order_by: 152
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_waste_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: waste_to_power_electricity_installed_flexible_capacities
- label: biomass_to_power
  color: "#6AB04C"
  order_by: 154
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_wood_pellets_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: wood_pellets_to_power_electricity_installed_flexible_capacities
- label: power_to_synthetic_kerosene
  color: "#74ffff"
  order_by: 160
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_synthetic_kerosene_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_synthetic_kerosene_electricity_installed_flexible_capacities

- label: residual_load_excess_peak
  color: "blue"
  order_by: 200
  group: heat_network
  is_target_line: true
  gquery: heat_network_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_capacities
  key: excess_peak_heat_network_installed_flexible_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 205
  group: heat_network
  is_target_line: true
  gquery: heat_network_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_capacities
  key: shortage_peak_heat_network_installed_flexible_capacities
- label: heat_network_storage
  color: "#0984E3"
  order_by: 210
  group: heat_network
  is_target_line: false
  gquery: heat_network_demand_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: storage_input_heat_network_installed_flexible_capacities
- label: coal_to_heat
  color: "#000000"
  order_by: 240
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_coal_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: coal_to_heat_heat_network_installed_flexible_capacities
- label: gas_to_heat
  color: "#CED6E0"
  order_by: 242
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_gas_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: gas_to_heat_heat_network_installed_flexible_capacities
- label: hydrogen_to_heat
  color: "#77dd99"
  order_by: 244
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_hydrogen_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: hydrogen_to_heat_heat_network_installed_flexible_capacities
- label: oil_to_heat
  color: "#7f2704"
  order_by: 246
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_oil_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: oil_to_heat_heat_network_installed_flexible_capacities
- label: power_to_heat_for_district_heating
  color: "#FFA502"
  order_by: 248
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_power_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_heat_heat_network_installed_flexible_capacities
- label: heat_network_storage
  color: "#0984E3"
  order_by: 212
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: storage_output_heat_network_installed_flexible_capacities
- label: waste_to_heat
  color: "#006266"
  order_by: 250
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_waste_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: waste_to_heat_heat_network_installed_flexible_capacities
- label: biomass_to_heat
  color: "#6AB04C"
  order_by: 252
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_wood_pellets_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: wood_pellets_to_heat_heat_network_installed_flexible_capacities

- label: residual_load_excess_peak
  color: "blue"
  order_by: 300
  group: hydrogen
  is_target_line: true
  gquery: hydrogen_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_capacities
  key: excess_peak_hydrogen_installed_flexible_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 310
  group: hydrogen
  is_target_line: true
  gquery: hydrogen_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_capacities
  key: shortage_peak_hydrogen_installed_flexible_capacities
- label: depleted_gas_field
  color: "#87CEEB"
  order_by: 320
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_demand_flexible_storage_depleted_gas_field_capacity
  output_element_key: installed_flexible_capacities
  key: storage_depleted_gas_field_input_hydrogen_installed_flexible_capacities
- label: salt_cavern
  color: "#5e9aa4"
  order_by: 330
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_demand_flexible_storage_salt_cavern_capacity
  output_element_key: installed_flexible_capacities
  key: storage_salt_cavern_input_hydrogen_installed_flexible_capacities
- label: depleted_gas_field
  color: "#87CEEB"
  order_by: 340
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_storage_depleted_gas_field_capacity
  output_element_key: installed_flexible_capacities
  key: storage_depleted_gas_field_output_hydrogen_installed_flexible_capacities
- label: salt_cavern
  color: "#5e9aa4"
  order_by: 350
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_storage_salt_cavern_capacity
  output_element_key: installed_flexible_capacities
  key: storage_salt_cavern_output_hydrogen_installed_flexible_capacities
- label: energy_hydrogen_steam_methane_reformer_dispatchable
  color: "#BEC3C8"
  order_by: 360
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_steam_methane_reformer_capacity
  output_element_key: installed_flexible_capacities
  key: steam_methane_reformer_dispatchable_hydrogen_installed_flexible_capacities
- label: energy_hydrogen_ammonia_reformer_dispatchable
  color: "#BEC3C8"
  order_by: 365
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_ammonia_reformer_capacity
  output_element_key: installed_flexible_capacities
  key: energy_hydrogen_ammonia_reformer_dispatchable_hydrogen_installed_flexible_capacities  
- label: energy_hydrogen_autothermal_reformer_dispatchable
  color: "#A59990"
  order_by: 370
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_autothermal_reformer_capacity
  output_element_key: installed_flexible_capacities
  key: autothermal_reformer_dispatchable_hydrogen_installed_flexible_capacities
- label: energy_imported_hydrogen_backup
  color: "#A7A1C5"
  order_by: 380
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_import_backup_capacity
  output_element_key: installed_flexible_capacities
  key: imported_hydrogen_backup_hydrogen_installed_flexible_capacities
- label: energy_export_hydrogen_backup
  color: "#667D94"
  order_by: 390
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_demand_flexible_export_backup_capacity
  output_element_key: installed_flexible_capacities
  key: exported_hydrogen_backup_hydrogen_installed_flexible_capacities


- label: residual_load_excess_peak
  color: "blue"
  order_by: 400
  group: network_gas
  is_target_line: true
  gquery: network_gas_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_capacities
  key: excess_peak_network_gas_installed_flexible_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 405
  group: network_gas
  is_target_line: true
  gquery: network_gas_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_capacities
  key: shortage_peak_network_gas_installed_flexible_capacities
- label: network_gas_storage
  color: "#b8b5ff"
  order_by: 410
  group: network_gas
  is_target_line: false
  gquery: network_gas_demand_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: storage_input_network_gas_installed_flexible_capacities
- label: network_gas_storage
  color: "#b8b5ff"
  order_by: 412
  group: network_gas
  is_target_line: false
  gquery: network_gas_production_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: storage_output_network_gas_installed_flexible_capacities
