---
- label: residual_load_excess_peak
  color: "blue"
  order_by: 100
  group: electricity
  is_target_line: true
  gquery: electricity_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_carriers_capacities
  key: excess_peak_electricity_installed_flexible_carriers_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 105
  group: electricity
  is_target_line: true
  gquery: electricity_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_carriers_capacities
  key: shortage_peak_electricity_installed_flexible_carriers_capacities
- label: electricity_interconnection_export
  color: "#77dd99"
  order_by: 120
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_export_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: export_interconnection_electricity_installed_flexible_carriers_capacities
- label: power_to_heat
  color: "#F6E58D"
  order_by: 126
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_heat_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: power_to_heat_electricity_installed_flexible_carriers_capacities
- label: power_to_hydrogen
  color: "#dd9977"
  order_by: 128
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_hydrogen_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: power_to_hydrogen_electricity_installed_flexible_carriers_capacities
- label: electricity_storage
  color: "#dd77bb"
  order_by: 110
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: power_to_power_input_electricity_installed_flexible_carriers_capacities
- label: coal_to_power
  color: "#000000"
  order_by: 140
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_coal_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: coal_to_power_electricity_installed_flexible_carriers_capacities
- label: gas_to_power
  color: "#969696"
  order_by: 142
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_gas_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: gas_to_power_electricity_installed_flexible_carriers_capacities
- label: hydrogen_to_power
  color: "#a3def7"
  order_by: 141
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_hydrogen_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: hydrogen_to_power_electricity_installed_flexible_carriers_capacities
- label: electricity_interconnection_import
  color: "#77bbdd"
  order_by: 119
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_import_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: import_interconnection_electricity_installed_flexible_carriers_capacities
- label: nuclear_to_power
  color: "#fd8d3c"
  order_by: 146
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_nuclear_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: nuclear_to_power_electricity_installed_flexible_carriers_capacities
- label: oil_to_power
  color: "#7f2704"
  order_by: 148
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_oil_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: oil_to_power_electricity_installed_flexible_carriers_capacities
- label: electricity_storage
  color: "#dd77bb"
  order_by: 112
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: power_to_power_output_electricity_installed_flexible_carriers_capacities
- label: waste_to_power
  color: "#006266"
  order_by: 152
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_waste_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: waste_to_power_electricity_installed_flexible_carriers_capacities
- label: biomass_to_power
  color: "#6AB04C"
  order_by: 154
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_wood_pellets_to_power_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: wood_pellets__to_power_electricity_installed_flexible_carriers_capacities

- label: residual_load_excess_peak
  color: "blue"
  order_by: 200
  group: heat_network
  is_target_line: true
  gquery: heat_network_imbalance_inflexible_carriers_excess_peak
  output_element_key: installed_flexible_carriers_capacities
  key: excess_peak_heat_network_installed_flexible_carriers_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 205
  group: heat_network
  is_target_line: true
  gquery: heat_network_imbalance_inflexible_carriers_shortage_peak
  output_element_key: installed_flexible_carriers_capacities
  key: shortage_peak_heat_network_installed_flexible_carriers_capacities
- label: heat_network_storage
  color: "#0984E3"
  order_by: 210
  group: heat_network
  is_target_line: false
  gquery: heat_network_demand_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: storage_input_heat_network_installed_flexible_carriers_capacities
- label: coal_to_heat
  color: "#000000"
  order_by: 240
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_coal_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: coal_to_heat_heat_network_installed_flexible_carriers_capacities
- label: gas_to_heat
  color: "#CED6E0"
  order_by: 242
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_gas_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: gas_to_heat_heat_network_installed_flexible_carriers_capacities
- label: hydrogen_to_heat
  color: "#F9CA24"
  order_by: 244
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_hydrogen_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: hydrogen_to_heat_heat_network_installed_flexible_carriers_capacities
- label: oil_to_heat
  color: "#7f2704"
  order_by: 246
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_oil_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: oil_to_heat_heat_network_installed_flexible_carriers_capacities
- label: power_to_heat_network
  color: "#F6E58D"
  order_by: 248
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_power_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: power_to_heat_heat_network_installed_flexible_carriers_capacities
- label: heat_network_storage
  color: "#0984E3"
  order_by: 212
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: storage_output_heat_network_installed_flexible_carriers_capacities
- label: waste_to_heat
  color: "#006266"
  order_by: 250
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_waste_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: waste_to_heat_heat_network_installed_flexible_carriers_capacities
- label: biomass_to_heat
  color: "#6AB04C"
  order_by: 252
  group: heat_network
  is_target_line: false
  gquery: heat_network_production_flexible_wood_pellets_to_heat_carriers_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: wood_pellets_to_heat_heat_network_installed_flexible_carriers_capacities

- label: residual_load_excess_peak
  color: "blue"
  order_by: 300
  group: hydrogen
  is_target_line: true
  gquery: hydrogen_imbalance_inflexible_carriers_excess_peak
  output_element_key: installed_flexible_carriers_capacities
  key: excess_peak_hydrogen_installed_flexible_carriers_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 305
  group: hydrogen
  is_target_line: true
  gquery: hydrogen_imbalance_inflexible_carriers_shortage_peak
  output_element_key: installed_flexible_carriers_capacities
  key: shortage_peak_hydrogen_installed_flexible_carriers_capacities
- label: hydrogen_storage
  color: "#87CEEB"
  order_by: 310
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_demand_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: storage_input_hydrogen_installed_flexible_carriers_capacities
- label: hydrogen_storage
  color: "#87CEEB"
  order_by: 312
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: storage_output_hydrogen_installed_flexible_carriers_capacities

- label: residual_load_excess_peak
  color: "blue"
  order_by: 400
  group: network_gas
  is_target_line: true
  gquery: network_gas_imbalance_inflexible_carriers_excess_peak
  output_element_key: installed_flexible_carriers_capacities
  key: excess_peak_network_gas_installed_flexible_carriers_capacities
- label: residual_load_shortage_peak
  color: "red"
  order_by: 405
  group: network_gas
  is_target_line: true
  gquery: network_gas_imbalance_inflexible_carriers_shortage_peak
  output_element_key: installed_flexible_carriers_capacities
  key: shortage_peak_network_gas_installed_flexible_carriers_capacities
- label: network_gas_storage
  color: "#A4B0BE"
  order_by: 410
  group: network_gas
  is_target_line: false
  gquery: network_gas_demand_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: storage_input_network_gas_installed_flexible_carriers_capacities
- label: network_gas_storage
  color: "#A4B0BE"
  order_by: 412
  group: network_gas
  is_target_line: false
  gquery: network_gas_production_flexible_storage_capacity
  output_element_key: installed_flexible_carriers_capacities
  key: storage_output_network_gas_installed_flexible_carriers_capacities
