---
- label: agriculture_final_demand_hydrogen_for_mekko
  color: "#6AB04C"
  order_by: 100
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: agriculture_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: agriculture_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_final_demand_hydrogen_for_mekko
  color: "#416B86"
  order_by: 110
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko
  color: "#74B9FF"
  order_by: 120
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_power_plants_hydrogen_for_mekko
  color: "#FF8C8C"
  order_by: 130
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_power_plants_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_power_plants_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_export_hydrogen_baseload_for_mekko
  color: "#485460"
  order_by: 140
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_export_hydrogen_baseload_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_export_hydrogen_baseload_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_export_hydrogen_backup_for_mekko
  color: "#667D94"
  order_by: 150
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_export_hydrogen_backup_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_export_hydrogen_backup_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_hydrogen_storage_unused_for_mekko
  color: "#98B2CC"
  order_by: 160
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_storage_unused_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_storage_excess_for_mekko_demand_mekko_of_hydrogen_network
- label: transport_losses
  color: "#FF0000"
  order_by: 170
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: losses_hydrogen_energetic_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: transport_losses_demand_mekko_of_hydrogen_network  
- label: transport_final_demand_hydrogen_for_mekko
  color: "#0984E3"
  order_by: 180
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: transport_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: transport_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: bunkers_final_demand_hydrogen_for_mekko
  color: "#8B4513"
  order_by: 190
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: bunkers_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: bunkers_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: households_inidividual_heater_hydrogen_for_mekko
  color: "#E07033"
  order_by: 200
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_inidividual_heater_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: households_inidividual_heater_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: buildings_inidividual_heater_hydrogen_for_mekko
  color: "#fabd16"
  order_by: 210
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: buildings_inidividual_heater_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: buildings_inidividual_heater_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko
  color: "#228B22"
  order_by: 220
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_heat_from_hydrogen_for_mekko
  color: "#E69567"
  order_by: 230
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_from_hydrogen_for_mekko
  is_1990:
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_heat_from_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_heat_from_hydrogen_for_mekko
  color: "#2e4c5e"
  order_by: 240
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: industry_heat_from_hydrogen_for_mekko
  is_1990:
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_heat_from_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_synthetic_products_from_hydrogen_for_mekko
  color: "#7bed9f"
  order_by: 250
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_synthetic_products_from_hydrogen_for_mekko
  is_1990:
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_synthetic_products_from_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: hydrogen_demand_transformation_chemical_fertilizers_industry
  color: "#ddd3d3"
  group: demand
  order_by: 260
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_demand_transformation_chemical_fertilizers_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: hydrogen_demand_transformation_chemical_fertilizers_industry_mekko_of_hydrogen_network
- label: hydrogen_demand_transformation_chemical_other_industry
  color: "#f8f1f1"
  order_by: 270
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_demand_transformation_chemical_other_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: hydrogen_demand_transformation_chemical_other_industry_mekko_of_hydrogen_network
- label: hydrogen_demand_transformation_chemical_refineries_industry
  color: "#747373"
  order_by: 280
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_demand_transformation_chemical_refineries_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: hydrogen_demand_transformation_chemical_refineries_industry_mekko_of_hydrogen_network



- label: industry_residual_hydrogen_for_mekko
  color: "#006400"
  order_by: 300
  group: supply
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: industry_residual_hydrogen_for_mekko
  is_1990:
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_residual_hydrogen_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_flexibility_p2g_electricity_for_mekko
  color: "#786FA6"
  order_by: 310
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_flexibility_p2g_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_flexibility_p2g_electricity_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_electrolysis_wind_electricity_for_mekko
  color: "#63A1C9"
  order_by: 320
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_electrolysis_wind_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_electrolysis_wind_electricity_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_hybrid_electrolysis_wind_electricity_for_mekko
  color: "#7487FF"
  order_by: 325
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_hybrid_electrolysis_wind_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_hybrid_electrolysis_wind_electricity_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_biomass_gasification_ccs_for_mekko
  color: "#5D7929"
  order_by: 330
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_biomass_gasification_ccs_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_biomass_gasification_ccs_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_biomass_gasification_for_mekko
  color: "#A2D679"
  order_by: 340
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_biomass_gasification_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_biomass_gasification_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_electrolysis_solar_electricity_for_mekko
  color: "#FDE97B"
  order_by: 350
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_electrolysis_solar_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_electrolysis_solar_electricity_for_mekko_supply_mekko_of_hydrogen_network  
- label: energy_hydrogen_steam_methane_reformer_must_run_for_mekko
  color: "#8A8F94"
  order_by: 360
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_must_run_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_steam_methane_reformer_must_run_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_steam_methane_reformer_ccs_must_run_for_mekko
  color: "#DFE4EA"
  order_by: 370
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_ccs_must_run_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_steam_methane_reformer_ccs_must_run_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_steam_methane_reformer_dispatchable_for_mekko
  color: "#BEC3C8"
  order_by: 380
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_dispatchable_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_steam_methane_reformer_dispatchable_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_autothermal_reformer_must_run_for_mekko
  color: "#82776F"
  order_by: 390
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_autothermal_reformer_must_run_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_autothermal_reformer_must_run_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_autothermal_reformer_ccs_must_run_for_mekko
  color: "#D5C6BA"
  order_by: 400
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_autothermal_reformer_ccs_must_run_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_autothermal_reformer_ccs_must_run_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_autothermal_reformer_dispatchable_for_mekko
  color: "#A59990"
  order_by: 410
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_autothermal_reformer_dispatchable_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_autothermal_reformer_dispatchable_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_ammonia_reformer_must_run_for_mekko
  color: "#109C91"
  order_by: 420
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_ammonia_reformer_must_run_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_ammonia_reformer_must_run_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_ammonia_reformer_dispatchable_for_mekko
  color: "#1ce6d6"
  order_by: 430
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_ammonia_reformer_dispatchable_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_ammonia_reformer_dispatchable_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_import_liquid_hydrogen_for_mekko
  color: "#524A79"
  order_by: 440
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_import_liquid_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_import_liquid_hydrogen_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_import_lohc_for_mekko
  color: "#8373D0"
  order_by: 450
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_import_lohc_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_import_lohc_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_imported_hydrogen_baseload
  color: "#C6C2DA"
  order_by: 460
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_import_hydrogen_baseload_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_import_hydrogen_baseload_for_mekko_supply_mekko_of_hydrogen_network    
- label: energy_imported_hydrogen_backup
  color: "#A7A1C5"
  order_by: 470
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_import_hydrogen_backup_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_import_hydrogen_backup_for_mekko_supply_mekko_of_hydrogen_network    
- label: hydrogen_supply_transformation_chemical_fertilizers_industry
  color: "#d8eded"
  order_by: 480
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_supply_transformation_chemical_fertilizers_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: hydrogen_supply_transformation_chemical_fertilizers_industry_mekko_of_hydrogen_network
- label: hydrogen_supply_transformation_chemical_other_industry
  color: "#e6fffe"
  order_by: 490
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_supply_transformation_chemical_other_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: hydrogen_supply_transformation_chemical_other_industry_mekko_of_hydrogen_network
- label: hydrogen_supply_transformation_chemical_refineries_industry
  color: "#697a7a"
  order_by: 500
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_supply_transformation_chemical_refineries_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: hydrogen_supply_transformation_chemical_refineries_industry_mekko_of_hydrogen_network

