---
- label: agriculture_final_demand_hydrogen_for_mekko
  color: "#6AB04C"
  order_by: 6
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: agriculture_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: agriculture_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_final_demand_hydrogen_for_mekko
  color: "#416B86"
  order_by: 5
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko
  color: "#74B9FF"
  order_by: 4
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_final_demand_for_chemical_fertilizers_hydrogen_non_energetic_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_power_plants_hydrogen_for_mekko
  color: "#FF8C8C"
  order_by: 2
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_power_plants_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_power_plants_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_import_hydrogen_for_mekko
  color: "#A7A1C5"
  order_by: 10
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_import_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_import_hydrogen_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_steam_methane_reformer_for_mekko
  color: "#DFE4EA"
  order_by: 17
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_steam_methane_reformer_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_steam_methane_reformer_ccs_for_mekko
  color: "#A4B0BE"
  order_by: 16
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_steam_methane_reformer_ccs_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_steam_methane_reformer_ccs_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_flexibility_p2g_electricity_for_mekko
  color: "#786FA6"
  order_by: 13
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_flexibility_p2g_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_flexibility_p2g_electricity_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_electrolysis_solar_electricity_for_mekko
  color: "#FDE97B"
  order_by: 14
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_electrolysis_solar_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_electrolysis_solar_electricity_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_electrolysis_wind_electricity_for_mekko
  color: "#63A1C9"
  order_by: 15
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_electrolysis_wind_electricity_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_electrolysis_wind_electricity_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_biomass_gasification_ccs_for_mekko
  color: "#A2D679"
  order_by: 12
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_biomass_gasification_ccs_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_biomass_gasification_ccs_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_hydrogen_biomass_gasification_for_mekko
  color: "#A2D679"
  order_by: 11
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_hydrogen_biomass_gasification_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_hydrogen_biomass_gasification_for_mekko_supply_mekko_of_hydrogen_network
- label: energy_export_hydrogen_for_mekko
  color: "#485460"
  order_by: 1
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_export_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_export_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: transport_losses
  color: "#FF0000"
  order_by: 18
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: losses_hydrogen_energetic_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: transport_losses_demand_mekko_of_hydrogen_network
- label: transport_final_demand_hydrogen_for_mekko
  color: "#0984E3"
  order_by: 3
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: transport_final_demand_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: transport_final_demand_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: households_inidividual_hybrid_heat_pump_hydrogen_for_mekko
  color: "#E34234"
  order_by: 8
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_inidividual_hybrid_heat_pump_hydrogen_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: households_inidividual_hybrid_heat_pump_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko
  color: "#228B22"
  order_by: 4
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: industry_final_demand_for_chemical_other_hydrogen_non_energetic_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_heat_from_hydrogen_for_mekko
  color: "#E69567"
  order_by: 7
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_from_hydrogen_for_mekko
  is_1990:
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_heat_from_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
- label: energy_synthetic_products_from_hydrogen_for_mekko
  color: "#7bed9f"
  order_by: 8
  group: demand
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_synthetic_products_from_hydrogen_for_mekko
  is_1990:
  dependent_on:
  output_element_key: mekko_of_hydrogen_network
  key: energy_synthetic_products_from_hydrogen_for_mekko_demand_mekko_of_hydrogen_network
