---
- label: households
  color: "#E07033"
  order_by: 1
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_households_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_households_oil_mekko_of_oil_mix
- label: buildings
  color: "#fabd16"
  order_by: 2
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_buildings_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_buildings_oil_mekko_of_oil_mix
- label: industry
  color: "#228B22"
  order_by: 3
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_industry_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_industry_oil_mekko_of_oil_mix
- label: industry_non_energetic
  color: "#a0de23"
  order_by: 4
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_industry_non_energetic_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_industry_non_energetic_oil_mekko_of_oil_mix
- label: agriculture
  color: "#6AB04C"
  order_by: 5
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_agriculture_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_agriculture_oil_mekko_of_oil_mix
- label: transport
  color: "#0984E3"
  order_by: 6
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_transport_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_transport_oil_mekko_of_oil_mix
- label: bunkers
  color: "#7ed9cd"
  order_by: 7
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_bunkers_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_bunkers_oil_mekko_of_oil_mix
- label: other
  color: "#ff96c4"
  order_by: 8
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_other_sector_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_other_sector_oil_mekko_of_oil_mix
- label: other_non_energetic
  color: "#fa4393"
  order_by: 9
  group: sector
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_other_sector_non_energetic_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_other_sector_non_energetic_oil_mekko_of_oil_mix

- label: diesel
  color: "#645070"
  order_by: 10
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_diesel
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_diesel_mekko_of_oil_mix
- label: biodiesel
  color: "#c7a0de"
  order_by: 11
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_biodiesel
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_biodiesel_mekko_of_oil_mix
- label: kerosene
  color: "#855f72"
  order_by: 12
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_kerosene
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_kerosene_mekko_of_oil_mix
- label: bio_kerosene
  color: "#dea0bf"
  order_by: 13
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_bio_kerosene
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_bio_kerosene_mekko_of_oil_mix
- label: lpg
  color: "#a1862d"
  order_by: 14
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_lpg
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_lpg_mekko_of_oil_mix
- label: naphtha
  color: "#F3CA4E"
  order_by: 15
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_naphtha
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_naphtha_mekko_of_oil_mix
- label: bio_naphtha
  color: "#F0D890"
  order_by: 20
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_bio_naphtha
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_bio_naphtha_mekko_of_oil_mix
- label: other_oil
  color: "#82685c"
  order_by: 25
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_other_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_other_oil_mekko_of_oil_mix
- label: other_bio_oil
  color: "#d4aa96"
  order_by: 30
  group: product
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_other_bio_oil
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_oil_mix
  key: final_demand_other_bio_oil_mekko_of_oil_mix
