---
- label: households_flexibility_p2p_electricity
  color: "#dd33cc"
  order_by: 300
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_flexibility_p2p_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: households_flexibility_p2p_electricity_flex_merit_order_hourly_flexibility
- label: transport_car_using_electricity
  color: "#dd77bb"
  order_by: 305
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: transport_car_flexibility_p2p_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: transport_car_using_electricity_flex_merit_order_hourly_flexibility
- label: transport_bus_using_electricity
  color: "#f78fb4"
  order_by: 310
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: transport_bus_flexibility_p2p_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: transport_bus_using_electricity_flex_merit_order_hourly_flexibility
- label: transport_truck_using_electricity
  color: "#db4270"
  order_by: 315
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: transport_truck_flexibility_p2p_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: transport_truck_using_electricity_flex_merit_order_hourly_flexibility
- label: transport_van_using_electricity
  color: "#c91042"
  order_by: 320
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: transport_van_flexibility_p2p_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: transport_van_using_electricity_flex_merit_order_hourly_flexibility
- label: energy_hydrogen_flexibility_p2g_electricity
  color: "#dd9977"
  order_by: 200
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_hydrogen_flexibility_p2g_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_hydrogen_flexibility_p2g_electricity_flex_merit_order_hourly_flexibility
- label: energy_export_electricity
  color: "#77dd99"
  order_by: 400
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_export_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_export_electricity_flex_merit_order_hourly_flexibility
- label: energy_flexibility_curtailment_electricity
  color: "#77bbdd"
  order_by: 410
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_flexibility_curtailment_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_curtailment_electricity_flex_merit_order_hourly_flexibility
- label: energy_flexibility_load_shifting_electricity_input
  color: "#EC7063"
  order_by: 411
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_flexibility_load_shifting_electricity_input_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_load_shifting_electricity_input_flex_merit_order_hourly_flexibility
- label: energy_flexibility_load_shifting_electricity_output
  color: "#F5B7B1"
  order_by: 412
  group: flex
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_flexibility_load_shifting_electricity_output_curve
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_load_shifting_electricity_output_flex_merit_order_hourly_flexibility
- label: baseload_demand
  color: "#dce9f7"
  order_by: 100
  group:
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_demand_inflexible_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: total_demand_area_merit_order_hourly_flexibility
- label: baseload_demand
  color: "#CC0000"
  order_by: 105
  group:
  show_at_first:
  is_target_line: true
  target_line_position:
  gquery: total_demand
  is_1990:
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: total_demand_line_merit_order_hourly_flexibility
- label: industry_flexibility_p2h_electricity
  color: "#8B0000"
  order_by: 205
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: industry_flexibility_p2h_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: industry_flexibility_p2h_electricity_flex_merit_order_hourly_flexibility
- label: agriculture_flexibility_p2h_electricity
  color: "#FFD700"
  order_by: 210
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: agriculture_flexibility_p2h_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: agriculture_flexibility_p2h_electricity_flex_merit_order_hourly_flexibility
- label: energy_flexibility_pumped_storage_electricity
  color: "#416B86"
  order_by: 310
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_flexibility_pumped_storage_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_pumped_storage_electricity_flex_merit_order_hourly_flexibility
- label: energy_flexibility_mv_batteries_electricity
  color: "#5a7bc4"
  order_by: 315
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_flexibility_mv_batteries_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_mv_batteries_electricity_flex_merit_order_hourly_flexibility
- label: energy_flexibility_opac_electricity
  color: "#385ba6"
  order_by: 320
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_flexibility_hv_opac_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_opac_electricity_flex_merit_order_hourly_flexibility
- label: energy_flexibility_flow_batteries_electricity
  color: "#162442"
  order_by: 325
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_flexibility_flow_batteries_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_flexibility_flow_batteries_electricity_flex_merit_order_hourly_flexibility
- label: energy_heat_flexibility_p2h_heatpump_ht_electricity
  color: "#f2d22e"
  order_by: 215
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_flexibility_p2h_heatpump_ht_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_heat_flexibility_p2h_heatpump_ht_electricity_flex_merit_order_hourly_flexibility
- label: energy_heat_flexibility_p2h_heatpump_mt_electricity
  color: "#F6E58D"
  order_by: 216
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_flexibility_p2h_heatpump_mt_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_heat_flexibility_p2h_heatpump_mt_electricity_flex_merit_order_hourly_flexibility
- label: energy_heat_flexibility_p2h_boiler_ht_electricity
  color: "#ff7802"
  order_by: 210
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_flexibility_p2h_boiler_ht_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_heat_flexibility_p2h_boiler_ht_electricity_flex_merit_order_hourly_flexibility
- label: energy_heat_flexibility_p2h_boiler_mt_electricity
  color: "#FFA502"
  order_by: 211
  group: flex
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: energy_heat_flexibility_p2h_boiler_mt_electricity_input_curve
  is_1990: false
  dependent_on:
  output_element_key: merit_order_hourly_flexibility
  key: energy_heat_flexibility_p2h_boiler_mt_electricity_flex_merit_order_hourly_flexibility
