---
- label: network_gas_demand
  color: "#FF0000"
  order_by: 100
  group:
  show_at_first:
  is_target_line: true
  target_line_position:
  gquery: network_gas_demand_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_production
  key: network_gas_demand_network_gas_production
- label: natural_gas_production
  color: "#A4B0BE"
  order_by: 200
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_extraction_network_gas_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: natural_gas_production_network_gas_production
- label: natural_gas_import
  color: "#666666"
  order_by: 210
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_import_network_gas_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: natural_gas_import_network_gas_production
- label: natural_gas_production_industry_transformation
  color: "#121212"
  order_by: 215
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_network_gas_industry_transformation_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: natural_gas_production_industry_transformation_network_gas_production
- label: propane_import
  color: "#808080"
  order_by: 250
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: propane_network_gas_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: propane_network_gas_production
- label: greengas_dry_biomass
  color: "#4CACBC"
  order_by: 300
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: greengas_gasification_dry_biomass_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: greengas_dry_biomass_network_gas_production
- label: greengas_wet_biomass
  color: "#6CC4A1"
  order_by: 305
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: greengas_gasification_wet_biomass_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: greengas_wet_biomass_network_gas_production
- label: greengas_upgrade_biogas
  color: "#A0D995"
  order_by: 310
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: greengas_upgrade_biogas_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: greengas_upgrade_biogas_network_gas_production
- label: greengas_production_industry_transformation
  color: "#6f9169"
  order_by: 315
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: greengas_network_gas_industry_transformation_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: greengas_network_gas_industry_transformation_output_curve_network_gas_production
- label: lng_production
  color: "#F6E58D"
  order_by: 220
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lng_network_gas_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: lng_production_network_gas_production
- label: network_gas_storage_output
  color: "#DFE4EA"
  order_by: 400
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: storage_network_gas_output_curve
  is_1990: false
  dependent_on:
  output_element_key: network_gas_production
  key: network_gas_storage_output_network_gas_production

