---
- label: eletricity_from_coal
  color: "#333333"
  order_by: 1
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: coal_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: coal_source_of_electricity_production
- label: eletricity_from_natural_gas
  color: "#CCCCCC"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: gas_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: natural_gas_source_of_electricity_production
- label: eletricity_from_oil
  color: "#854321"
  order_by: 8
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: oil_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: oil_source_of_electricity_production
- label: eletricity_from_nuclear
  color: "#E07033"
  order_by: 4
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: nuclear_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: nuclear_source_of_electricity_production
- label: eletricity_from_solid_biomass
  color: "#5D7929"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biomass_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: solid_biomass_source_of_electricity_production
- label: eletricity_from_wind
  color: "#63A1C9"
  order_by: 6
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: wind_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: wind_source_of_electricity_production
- label: eletricity_from_hydro
  color: "#87CEEB"
  order_by: 7
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: hydro_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: hydro_source_of_electricity_production
- label: eletricity_from_greengas
  color: "#92B940"
  order_by: 3
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: greengas_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: greengas_source_of_electricity_production
- label: eletricity_from_geothermal
  color: "#BA7D40"
  order_by: 9
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: geothermal_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: geothermal_source_of_electricity_production
- label: eletricity_from_waste
  color: "#394C19"
  order_by: 10
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: waste_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: waste_source_of_electricity_production
- label: eletricity_from_solar
  color: "#ADDE4C"
  order_by: 11
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: solar_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: solar_source_of_electricity_production
- label: demand_incl_export
  color: "#5D59C7"
  order_by: 14
  group: ''
  show_at_first: false
  is_target_line: true
  target_line_position: '1'
  gquery: present_demand_and_export_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: present_demand_and_export_source_of_electricity_production
- label: demand_incl_export
  color: "#5D59C7"
  order_by: 14
  group: ''
  show_at_first: false
  is_target_line: true
  target_line_position: '2'
  gquery: future_demand_and_export_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: future_demand_and_export_source_of_electricity_production
- label: domestic_demand
  color: "#FF0000"
  order_by: 15
  group: ''
  show_at_first: false
  is_target_line: true
  target_line_position: '1'
  gquery: present_demand_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: present_demand_source_of_electricity_production
- label: domestic_demand
  color: "#FF0000"
  order_by: 16
  group: ''
  show_at_first: false
  is_target_line: true
  target_line_position: '2'
  gquery: future_demand_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: future_demand_source_of_electricity_production
- label: eletricity_from_import
  color: "#4169E1"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: import_in_source_of_electricity_production
  is_1990: false
  dependent_on:
  output_element_key: source_of_electricity_production
  key: import_source_of_electricity_production
- label: eletricity_from_biogas
  color: "#32CD32"
  order_by: 12
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biogas_in_source_of_electricity_production
  is_1990:
  dependent_on:
  output_element_key: source_of_electricity_production
  key: biogas_source_of_electricity_production
- label: eletricity_from_hydrogen
  color: "#BFEFFF"
  order_by: 6
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_in_source_of_electricity_production
  is_1990: false
  dependent_on:
  output_element_key: source_of_electricity_production
  key: hydrogen_source_of_electricity_production
- label: eletricity_from_coal_gas
  color: "#7040c2"
  order_by: 1
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_gas_in_source_of_electricity_production
  is_1990: false
  dependent_on:
  output_element_key: source_of_electricity_production
  key: coal_gas_source_of_electricity_production
