---
- label: biomass_products
  color: "#5D7929"
  order_by: 6
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: biomass_products_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: biomass_products_source_of_heat_in_agriculture
- label: coal_and_derivatives
  color: "#333333"
  order_by: 2
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: coal_and_derivatives_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: coal_and_derivatives_source_of_heat_in_agriculture
- label: electricity
  color: "#4169E1"
  order_by: 5
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: electricity_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: electricity_source_of_heat_in_agriculture
- label: heat
  color: "#8B0000"
  order_by: 1
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: heat_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: heat_source_of_heat_in_agriculture
- label: natural_gas_and_derivatives
  color: "#CCCCCC"
  order_by: 3
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: natural_gas_and_derivatives_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: natural_gas_and_derivatives_source_of_heat_in_agriculture
- label: oil_and_derivatives
  color: "#854321"
  order_by: 4
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: oil_and_derivatives_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: oil_and_derivatives_source_of_heat_in_agriculture
- label: ambient_heat
  color: "#ADDE4C"
  order_by: 8
  group: agriculture
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: ambient_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: ambient_agriculture_source_of_heat_in_agriculture
- label: geothermal
  color: "#FF8400"
  order_by: 9
  group: agriculture
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: geothermal_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: geothermal_agriculture_source_of_heat_in_agriculture
- label: solar
  color: "#FFD900"
  order_by: 7
  group: agriculture
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: solar_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: solar_agriculture_source_of_heat_in_agriculture
- label: hydrogen
  color: "#87CEEB"
  order_by: 10
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_used_for_heating_in_agriculture
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: hydrogen_source_of_heat_in_agriculture
