---
- label: combined_offshore_power
  color: "#CC0000"
  order_by: 100
  is_target_line: true
  target_line_position:
  gquery: energy_power_offshore_combined_output_curve
  is_1990: false
  dependent_on:
  output_element_key: supply_offshore_solar_wind
  key: energy_power_offshore_combined_output_curve_supply_offshore_solar_wind

- label: energy_power_wind_turbine_offshore
  color: "#63A1C9"
  order_by: 200
  is_target_line: false
  target_line_position: ''
  gquery: energy_power_wind_turbine_offshore_output_curve
  is_1990: false
  dependent_on:
  output_element_key: supply_offshore_solar_wind
  key: energy_power_wind_turbine_offshore_output_curve_supply_offshore_solar_wind
- label: energy_power_hybrid_wind_turbine_offshore
  color: "#7487FF"
  order_by: 250
  is_target_line: false
  target_line_position: ''
  gquery: energy_power_hybrid_wind_turbine_offshore_output_curve
  is_1990: false
  dependent_on:
  output_element_key: supply_offshore_solar_wind
  key: energy_power_hybrid_wind_turbine_offshore_output_curve_supply_offshore_solar_wind
- label: energy_power_solar_pv_offshore
  color: "#ffcc00"
  order_by: 300
  is_target_line: false
  target_line_position: ''
  gquery: energy_power_solar_pv_offshore_output_curve
  is_1990: false
  dependent_on:
  output_element_key: supply_offshore_solar_wind
  key: energy_power_solar_pv_offshore_output_curve_supply_offshore_solar_wind

- label: energy_power_solar_pv_offshore_curtailed_electricity_output_curve
  color: "#AA14F0"
  order_by: 400
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: energy_power_offshore_solar_pv_curtailed_electricity_output_curve
  is_1990: 
  dependent_on: 
  output_element_key: supply_offshore_solar_wind
  key: energy_power_solar_pv_offshore_curtailed_electricity_output_curve_supply_offshore_solar_wind
- label: energy_power_hybrid_wind_turbine_offshore_curtailed_electricity
  color: "#B4BBEA"
  order_by: 410
  is_target_line: false
  target_line_position: ''
  gquery: energy_power_hybrid_wind_turbine_offshore_curtailed_electricity_output_curve
  is_1990: false
  dependent_on:
  output_element_key: supply_offshore_solar_wind
  key: energy_power_hybrid_wind_turbine_offshore_curtailed_electricity_output_curve_supply_offshore_solar_wind
  