---
- label: kerosene_planes
  color: "#A9A9A9"
  order_by: 1
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: fossil_kerosene_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: kerosene_planes_use_of_final_demand_in_international_transport
- label: synthetic_kerosene_planes
  color: "#74B9FF"
  order_by: 2
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: synthetic_kerosene_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: synthetic_kerosene_planes_use_of_final_demand_in_international_transport
- label: bio_kerosene_planes
  color: "#5D7929"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: bio_kerosene_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: bio_kerosene_planes_use_of_final_demand_in_international_transport
- label: heavy_fuel_oil_for_ships
  color: "#8B4513"
  order_by: 5
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heavy_fuel_oil_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: heavy_fuel_oil_for_ships_use_of_final_demand_in_international_transport
- label: lng_ships
  color: "#696969"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lng_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: lng_ships_use_of_final_demand_in_international_transport
