---
- label: cooling_demand
  color: "#ADD8E6"
  order_by: 4
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: cooling_demand_in_use_of_final_demand_in_buildings
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_buildings
  key: cooling_demand_use_of_final_demand_in_buildings
- label: appliances
  color: "#4169E1"
  order_by: 1
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: appliances_demand_in_use_of_final_demand_in_buildings
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_buildings
  key: electrical_appliances_use_of_final_demand_in_buildings
- label: heat_demand_buildings
  color: "#696969"
  order_by: 1
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heat_demand_buildings_in_use_of_final_demand_in_buildings
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_buildings
  key: heat_demand_buildings_use_of_final_demand_in_buildings
- label: lighting
  color: "#FFD700"
  order_by: 3
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lighting_demand_in_use_of_final_demand_in_buildings
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_buildings
  key: lighting_use_of_final_demand_in_buildings
