---
- label: biomass_products
  color: "#5D7929"
  order_by: 6
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_biomass_products_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: biomass_products_use_of_final_demand_in_agriculture
- label: coal_and_derivatives
  color: "#333333"
  order_by: 2
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_coal_and_derivatives_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: coal_and_derivatives_use_of_final_demand_in_agriculture
- label: electricity
  color: "#4169E1"
  order_by: 5
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_electricity_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: electricity_use_of_final_demand_in_agriculture
- label: ambient
  color: "#ADDE4C"
  order_by: 8
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_ambient_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: ambient_use_of_final_demand_in_agriculture
- label: heat
  color: "#8B0000"
  order_by: 1
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_heat_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: heat_use_of_final_demand_in_agriculture
- label: natural_gas_and_derivatives
  color: "#CCCCCC"
  order_by: 3
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_natural_gas_and_derivatives_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: natural_gas_and_derivatives_use_of_final_demand_in_agriculture
- label: oil_and_derivatives
  color: "#854321"
  order_by: 4
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_oil_and_derivatives_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: oil_and_derivatives_use_of_final_demand_in_agriculture
- label: geothermal
  color: "#FF8400"
  order_by: 9
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_geothermal_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: geothermal_use_of_final_demand_in_agriculture
- label: solar
  color: "#FFD900"
  order_by: 7
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_solar_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: solar_use_of_final_demand_in_agriculture
- label: hydrogen
  color: "#87CEEB"
  order_by: 9
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_hydrogen_in_agriculture
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_agriculture
  key: hydrogen_use_of_final_demand_in_agriculture
