# For the file structure, we have chosen for a split in fossil and non-fossil carriers, instead of a split between planes and ships.
# This is to show the carrier transition in the sector through this graph.
---
# Fossil carriers
- label: kerosene_planes
  color: "#A9A9A9"
  order_by: 100
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: fossil_kerosene_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: kerosene_planes_use_of_final_demand_in_international_transport
- label: synthetic_kerosene_planes
  color: "#74B9FF"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: synthetic_kerosene_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: synthetic_kerosene_planes_use_of_final_demand_in_international_transport
- label: heavy_fuel_oil_for_ships
  color: "#8B4513"
  order_by: 110
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heavy_fuel_oil_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: heavy_fuel_oil_for_ships_use_of_final_demand_in_international_transport

# Non-fossil carriers
- label: bio_kerosene_planes
  color: "#5D7929"
  order_by: 200
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: bio_kerosene_demand_international_aviation_transport_fuels
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: bio_kerosene_planes_use_of_final_demand_in_international_transport
- label: hydrogen_planes
  color: "#c9e9f6"
  order_by: 205
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: hydrogen_planes_use_of_final_demand_in_international_transport
- label: electricity_planes
  color: "#41b9e1"
  order_by: 210
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: electricity_planes_use_of_final_demand_in_international_transport



- label: lng_ships
  color: "#696969"
  order_by: 300
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lng_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: lng_ships_use_of_final_demand_in_international_transport
- label: bio_lng_ships
  color: "#006400"
  order_by: 301
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: bio_lng_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: bio_lng_ships_use_of_final_demand_in_international_transport
- label: hydrogen_ships
  color: "#87CEEB"
  order_by: 305
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: hydrogen_ships_use_of_final_demand_in_international_transport
- label: ammonia_ships
  color: "#1ce6d6"
  order_by: 310
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ammonia_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: ammonia_ships_use_of_final_demand_in_international_transport
- label: electricity_ships
  color: "#4169E1"
  order_by: 315
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: electricity_ships_use_of_final_demand_in_international_transport
- label: methanol_ships
  color: "#FF8C8C"
  order_by: 320
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: methanol_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: methanol_ships_use_of_final_demand_in_international_transport
- label: bio_methanol_ships
  color: "#6AB04C"
  order_by: 325
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: bio_methanol_demand_international_shipping
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_international_transport
  key: bio_methanol_ships_use_of_final_demand_in_international_transport
