---
- label: coal_and_derivatives
  color: "#333333"
  order_by: 10
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: coal_in_use_of_final_demand_in_industry_other_metals
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other_metals
  key: coal_and_derivatives_use_of_final_demand_in_industry_other_metals
- label: oil_and_derivatives
  color: "#854321"
  order_by: 20
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: oil_in_use_of_final_demand_in_industry_other_metals
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other_metals
  key: oil_and_derivatives_use_of_final_demand_in_industry_other_metals
- label: natural_gas_and_derivatives
  color: "#CCCCCC"
  order_by: 30
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: network_gas_in_use_of_final_demand_in_industry_other_metals
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other_metals
  key: natural_gas_and_derivatives_use_of_final_demand_in_industry_other_metals
- label: electricity
  color: "#4169E1"
  order_by: 40
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: electricity_in_use_of_final_demand_in_industry_other_metals
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other_metals
  key: electricity_use_of_final_demand_in_industry_other_metals
- label: heat
  color: "#8B0000"
  order_by: 50
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: steam_hot_water_in_use_of_final_demand_in_industry_other_metals
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_other_metals
  key: heat_use_of_final_demand_in_industry_other_metals
- label: hydrogen
  color: "#87CEEB"
  order_by: 60
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: hydrogen_in_use_of_final_demand_in_industry_other_metals
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other_metals
  key: hydrogen_use_of_final_demand_in_industry_other_metals
