---
- label: ambient
  color: "#ADDE4C"
  order_by: 8
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_ambient_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: ambient_aggregated_other_use_of_final_demand_in_industry_other
- label: biomass_products_energetic
  color: "#5D7929"
  order_by: 9
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_biomass_products_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: biomass_products_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: biomass_products_non_energetic
  color: "#006400"
  order_by: 10
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_biomass_products_in_other_non_specified_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: biomass_products_non_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: coal_energetic
  color: "#333333"
  order_by: 2
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_coal_and_coal_gas_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: coal_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: coal_non_energetic
  color: "#000000"
  order_by: 3
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_coal_and_coal_gas_in_other_non_specified_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: coal_and_coal_gas_non_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: cokes_energetic
  color: "#6971DC"
  order_by: 4
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_cokes_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: cokes_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: cokes_non_energetic
  color: "#5F34C8"
  order_by: 5
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_cokes_in_other_non_specified_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: cokes_non_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: electricity
  color: "#4169E1"
  order_by: 8
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_electricity_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: electricity_aggregated_other_use_of_final_demand_in_industry_other
- label: geothermal
  color: "#FF8400"
  order_by: 9
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_geothermal_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: geothermal_aggregated_other_use_of_final_demand_in_industry_other
- label: heat
  color: "#8B0000"
  order_by: 1
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_heat_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: heat_aggregated_other_use_of_final_demand_in_industry_other
- label: hydrogen_energetic
  color: "#87CEEB"
  order_by: 11
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_hydrogen_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: hydrogen_aggregated_other_use_of_final_demand_in_industry_other_energetic
- label: hydrogen_non_energetic
  color: "#45b3e0"
  order_by: 12
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_hydrogen_in_other_non_specified_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: hydrogen_aggregated_other_use_of_final_demand_in_industry_other_non_energetic
- label: network_gas_energetic
  color: "#CCCCCC"
  order_by: 4
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_natural_gas_and_derivatives_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: network_gas_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: network_gas_non_energetic
  color: "#A9A9A9"
  order_by: 5
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_natural_gas_and_derivatives_in_other_non_specified_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: network_gas_non_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: oil_energetic
  color: "#BA7D40"
  order_by: 6
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_oil_and_derivatives_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: oil_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: oil_and_derivatives_non_energetic
  color: "#854321"
  order_by: 7
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_oil_and_derivatives_in_other_non_specified_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: oil_and_derivatives_non_energetic_aggregated_other_use_of_final_demand_in_industry_other
- label: solar
  color: "#FFD900"
  order_by: 7
  group: aggregated_other
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_solar_in_other_non_specified_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_other
  key: solar_aggregated_other_use_of_final_demand_in_industry_other
