---
- label: ambient
  color: "#ADDE4C"
  order_by: 8
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_ambient_in_other_chemical_industry_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: ambient_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: biomass_products_energetic
  color: "#5D7929"
  order_by: 9
  group: other_chemical
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_biomass_products_in_other_chemical_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: biomass_products_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: biomass_products_non_energetic
  color: "#006400"
  order_by: 10
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_biomass_products_in_other_chemical_industry_non_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: biomass_products_non_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: coal_non_energetic
  color: "#333333"
  order_by: 2
  group: coal
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_coal_and_derivatives_in_other_chemical_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: coal_non_energetic_coal_use_of_final_demand_in_industry_chemical_other
- label: coal_and_derivatives_non_energetic
  color: "#000000"
  order_by: 3
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_coal_and_derivatives_in_other_chemical_industry_non_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: coal_and_derivatives_non_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: electricity
  color: "#4169E1"
  order_by: 8
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_electricity_in_other_chemical_industry_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: electricity_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: geothermal
  color: "#FF8400"
  order_by: 9
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_geothermal_in_other_chemical_industry_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: geothermal_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: heat
  color: "#8B0000"
  order_by: 1
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_heat_in_other_chemical_industry_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: heat_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: hydrogen
  color: "#87CEEB"
  order_by: 11
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_hydrogen_in_other_chemical_industry_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: hydrogen_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: network_gas_energetic
  color: "#CCCCCC"
  order_by: 4
  group: other_chemical
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_natural_gas_and_derivatives_in_other_chemical_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: network_gas_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: network_gas_non_energetic
  color: "#A9A9A9"
  order_by: 5
  group: other_chemical
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_natural_gas_and_derivatives_in_other_chemical_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: network_gas_non_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: oil_energetic
  color: "#BA7D40"
  order_by: 6
  group: other_chemical
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_oil_and_derivatives_in_other_chemical_industry_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: oil_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: oil_and_derivatives_non_energetic
  color: "#854321"
  order_by: 7
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_oil_and_derivatives_in_other_chemical_industry_non_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: oil_and_derivatives_non_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: solar
  color: "#FFD900"
  order_by: 7
  group: other_chemical
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: final_demand_of_solar_in_other_chemical_industry_energetic
  is_1990: 
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: solar_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: hydrogen_non_energetic
  color: "#BFEFFF"
  order_by: 12
  group: other_chemical
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_hydrogen_in_other_chemical_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: hydrogen_non_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
- label: methanol_non_energetic
  color: "#FF8C8C"
  order_by: 15
  group: other_chemical
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_methanol_in_other_chemical_industry_non_energetic
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_industry_chemical_other
  key: methanol_non_energetic_other_chemical_use_of_final_demand_in_industry_chemical_other
