---
- label: buildings_heating
  color: lightgreen
  order_by: 5
  group: buildings_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: buildings_heating_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: buildings_heating_user_profiles
- label: buildings_cooling
  color: lightgreen
  order_by: 10
  group: buildings_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: buildings_cooling_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: buildings_cooling_user_profiles
- label: buildings_appliances
  color: lightgreen
  order_by: 15
  group: buildings_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: buildings_appliances_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: buildings_appliances_user_profiles
- label: transport_e_cars
  color: lightgreen
  order_by: 100
  group: transport_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: transport_e_cars_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: transport_e_cars_user_profiles
- label: transport_e_buses
  color: lightgreen
  order_by: 105
  group: transport_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: transport_e_buses_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: transport_e_buses_user_profiles
- label: transport_e_trucks
  color: lightgreen
  order_by: 110
  group: transport_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: transport_e_trucks_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: transport_e_trucks_user_profiles
- label: transport_e_vans
  color: lightgreen
  order_by: 115
  group: transport_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: transport_e_vans_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: transport_e_vans_user_profiles
- label: transport_e_ships
  color: lightgreen
  order_by: 120
  group: transport_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: transport_e_ships_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: transport_e_ships_user_profiles
- label: transport_e_planes
  color: lightgreen
  order_by: 125
  group: transport_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: transport_e_planes_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: transport_e_planes_user_profiles
- label: industry_ict_electricity
  color: lightgreen
  order_by: 200
  group: industry_electricity_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_ict_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_ict_user_profiles
- label: industry_metals_electricity
  color: lightgreen
  order_by: 205
  group: industry_electricity_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_metals_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_metals_electricity_user_profiles
- label: industry_metals_heat
  color: lightgreen
  order_by: 210
  group: industry_heat_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_metals_heat_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_metals_heat_user_profiles
- label: industry_chemicals_electricity
  color: lightgreen
  order_by: 220
  group: industry_electricity_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_chemicals_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_chemicals_electricity_user_profiles
- label: industry_chemicals_heat
  color: lightgreen
  order_by: 225
  group: industry_heat_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_chemicals_heat_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_chemicals_heat_user_profiles
- label: industry_fertilizers_electricity
  color: lightgreen
  order_by: 230
  group: industry_electricity_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_fertilizers_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_fertilizers_electricity_user_profiles
- label: industry_fertilizers_heat
  color: lightgreen
  order_by: 235
  group: industry_heat_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_fertilizers_heat_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_fertilizers_heat_user_profiles
- label: industry_refineries_electricity
  color: lightgreen
  order_by: 240
  group: industry_electricity_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_refineries_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_refineries_electricity_user_profiles
- label: industry_refineries_heat
  color: lightgreen
  order_by: 245
  group: industry_heat_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_refineries_heat_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_refineries_heat_user_profiles
- label: industry_other_electricity
  color: lightgreen
  order_by: 26
  group: industry_electricity_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_other_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_other_electricity_user_profiles
- label: industry_other_heat
  color: lightgreen
  order_by: 250
  group: industry_heat_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: industry_other_heat_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: industry_other_heat_user_profiles
- label: hydro_power_river
  color: lightgreen
  order_by: 300
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: hydro_power_river_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: hydro_power_river_user_profiles
- label: wind_offshore_production
  color: lightgreen
  order_by: 305
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: wind_offshore_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: wind_offshore_production_user_profiles
- label: wind_onshore_production
  color: lightgreen
  order_by: 310
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: wind_onshore_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: wind_onshore_production_user_profiles
- label: wind_coastal_production
  color: lightgreen
  order_by: 315
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: wind_coastal_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: wind_coastal_production_user_profiles
- label: solar_pv_energy_power_solar_pv_solar_radiation_production
  color: lightgreen
  order_by: 320
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: solar_pv_energy_power_solar_pv_solar_radiation_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: solar_pv_energy_power_solar_pv_solar_radiation_user_profiles
- label: solar_pv_households_solar_pv_solar_radiation_production
  color: lightgreen
  order_by: 330
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: solar_pv_households_solar_pv_solar_radiation_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: solar_pv_households_solar_pv_solar_radiation_user_profiles
- label: solar_pv_buildings_solar_pv_solar_radiation_production
  color: lightgreen
  order_by: 340
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: solar_pv_buildings_solar_pv_solar_radiation_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: solar_pv_buildings_solar_pv_solar_radiation_user_profiles
- label: solar_pv_energy_power_solar_pv_offshore_production
  color: lightgreen
  order_by: 350
  group: electricity_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: solar_pv_energy_power_solar_pv_offshore_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: solar_pv_energy_power_solar_pv_offshore_user_profiles
- label: geothermal_heat_production
  color: lightgreen
  order_by: 400
  group: heat_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: geothermal_heat_production_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: geothermal_heat_production_user_profiles
- label: solar_thermal_heat_production
  color: lightgreen
  order_by: 405
  group: heat_production_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: solar_thermal_heat_production_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: solar_thermal_heat_production_user_profiles
- label: hydrogen_import
  color: lightgreen
  order_by: 500
  group: gas_import_export_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: hydrogen_import_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: hydrogen_import_user_profiles
- label: hydrogen_export
  color: lightgreen
  order_by: 505
  group: gas_import_export_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: hydrogen_export_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: hydrogen_export_user_profiles
- label: methane_import
  color: lightgreen
  order_by: 510
  group: gas_import_export_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: methane_import_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: methane_import_user_profiles
- label: methane_export
  color: lightgreen
  order_by: 515
  group: gas_import_export_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: methane_export_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: methane_export_user_profiles
- label: agriculture_electricity
  color: lightgreen
  order_by: 600
  group: agriculture_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: agriculture_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: agriculture_electricity_user_profiles
- label: agriculture_heat
  color: lightgreen
  order_by: 605
  group: agriculture_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: agriculture_heat_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: agriculture_heat_user_profiles
- label: households_cooling
  color: lightgreen
  order_by: 700
  group: households_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: households_cooling_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: households_cooling_user_profiles
- label: households_hot_water
  color: lightgreen
  order_by: 705
  group: households_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: households_hot_water_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: households_hot_water_user_profiles
- label: households_appliances
  color: lightgreen
  order_by: 710
  group: households_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: households_appliances_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: households_appliances_user_profiles
- label: bunkers_ships_electricity
  color: lightgreen
  order_by: 800
  group: bunkers_curves
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: bunkers_ships_electricity_curve
  is_1990:
  dependent_on:
  output_element_key: user_profiles
  key: electric_bunkers_navigation_user_profiles
