---
- label: ammonia
  color: "#1ce6d6" 
  order_by: 10 
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ammonia_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: ammonia_future_energy_imports

- label: biomass_products
  color: "#5D7929" 
  order_by: 20
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biomass_products_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: biomass_future_energy_imports

- label: coal_and_coal_products 
  color: "#333333" 
  order_by: 30
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_and_coal_products_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: coal_future_energy_imports

- label: crude_oil
  color: "#854321" 
  order_by: 40
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: crude_oil_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: crude_oil_future_energy_imports

- label: oil_products
  color: "#854321" 
  order_by: 45
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: oil_products_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: oil_products_future_energy_imports

- label: electricity
  color: "#4169E1" 
  order_by: 50
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: electricity_future_energy_imports

- label: heat 
  color: "#8B0000"
  order_by: 60
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heat_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: heat_future_future_energy_imports

- label: hydrogen_gaseous 
  color: "#88CCEE"
  order_by: 70
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_gaseous_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: hydrogen_gaseous_future_energy_imports

- label: hydrogen_liquid
  color: "#88CCEE" 
  order_by: 80
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_liquid_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: hydrogen_liquid_future_energy_imports

- label: hydrogen_lohc
  color: "#88CCEE" 
  order_by: 90
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_lohc_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: hydrogen_lohc_future_energy_imports

- label: lng 
  color: "#7f7f7f" 
  order_by: 100
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lng_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: lng_future_energy_imports

- label: natural_gas
  color: "#CCCCCC" 
  order_by: 110
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: natural_gas_future_energy_imports

- label: non_biogenic_waste
  color: "#7f7f7f" 
  order_by: 120
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: non_biogenic_waste_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: non_biogenic_waste_future_energy_imports  

- label: uranium_oxide
  color: "#E07033" 
  order_by: 140
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: uranium_oxide_in_future_energy_imports
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_imports
  key: uranium_oxide_future_energy_imports    
