---
- image: tractor_and_greenhouse.gif
  general_sub_header: "%/year"
  key: demand_agriculture_demand_growth
  position: 1
  sidebar_item_key: agriculture
  alt_output_element_key: use_of_final_demand_in_agriculture
  output_element_key: use_of_final_demand_in_agriculture
- image: tractor_and_greenhouse.gif
  key: demand_agriculture_heat
  position: 2
  sidebar_item_key: agriculture
  alt_output_element_key: source_of_heat_in_agriculture
  output_element_key: source_of_heat_in_agriculture
