---
- image: building_uncapped.gif
  general_sub_header: "%/year"
  key: demand_buildings_demand_growth
  position: 10
  sidebar_item_key: buildings
  alt_output_element_key: use_of_final_demand_in_buildings
  output_element_key: use_of_final_demand_in_buildings
- image: building_insulation.gif
  general_sub_header: heat_demand_reduction
  subheader_image: buildings_insulation_energy_label.png
  key: demand_buildings_insulation
  position: 2
  sidebar_item_key: buildings
  alt_output_element_key: effect_of_insulation_in_buildings
  output_element_key: use_of_final_demand_in_buildings
- image: building_heating_uncapped.gif
  group_sub_header: share
  key: demand_buildings_heating
  position: 3
  sidebar_item_key: buildings
  alt_output_element_key: source_of_heat_in_buildings
  output_element_key: source_of_heat_in_buildings
- image: building_cooling_uncapped.gif
  general_sub_header: share
  key: demand_buildings_cooling
  position: 5
  sidebar_item_key: buildings
  alt_output_element_key: source_of_cooling_in_buildings
  output_element_key: source_of_cooling_in_buildings
- image: building_appliances_uncapped.gif
  general_sub_header: "%/year"
  key: demand_buildings_appliances
  position: 7
  sidebar_item_key: buildings
  alt_output_element_key: use_of_electricity_in_buildings
  output_element_key: use_of_electricity_in_buildings
- image: building_lighting_uncapped.gif
  general_sub_header: share
  group_sub_header: "% of potential"
  key: demand_buildings_lighting
  position: 8
  sidebar_item_key: buildings
  alt_output_element_key: use_of_electricity_in_buildings
  output_element_key: use_of_electricity_in_buildings
