---
- key: demand_buildings_overview
  position: 0
  sidebar_item_key: buildings
  output_element_key: use_of_final_demand_in_buildings
- general_sub_header: number
  key: demand_buildings_stock
  position: 100
  sidebar_item_key: buildings
  output_element_key: use_of_final_demand_in_buildings
- key: demand_buildings_insulation
  position: 105
  sidebar_item_key: buildings
  alt_output_element_key:
  output_element_key: use_of_final_demand_in_buildings
- group_sub_header: of_heat_demand
  key: demand_buildings_heating
  position: 110
  sidebar_item_key: buildings
  alt_output_element_key: source_of_heat_in_buildings
  output_element_key: source_of_heat_in_buildings
- general_sub_header: share
  key: demand_buildings_cooling
  position: 115
  sidebar_item_key: buildings
  alt_output_element_key: source_of_cooling_in_buildings
  output_element_key: source_of_cooling_in_buildings
- general_sub_header: "%/year"
  key: demand_buildings_appliances
  position: 120
  sidebar_item_key: buildings
  output_element_key: source_of_appliances_in_buildings
- general_sub_header: share
  group_sub_header: "% of potential"
  key: demand_buildings_lighting
  position: 125
  sidebar_item_key: buildings
  alt_output_element_key: use_of_electricity_in_buildings
  output_element_key: use_of_electricity_in_buildings
- group_sub_header: "%/year"
  key: demand_buildings_demand_growth
  position: 135
  sidebar_item_key: buildings
  alt_output_element_key: use_of_final_demand_in_buildings
  output_element_key: use_of_final_demand_in_buildings

- group_sub_header: share
  key: demand_buildings_oil_mix
  position: 200
  sidebar_item_key: buildings
  output_element_key: mekko_of_oil_mix
  dependent_on: has_coal_oil_for_heating_built_environment
