---
- id: 7
  general_sub_header: change
  key: costs_combustion_investment
  position: 2
  sidebar_item_key: combustion
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
- id: 8
  general_sub_header: change
  key: costs_combustion_operational_and_maintenance
  position: 3
  sidebar_item_key: combustion
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
