---
- id: 41
  general_sub_header: maximum increase
  key: policy_cost_energy
  position: 1
  sidebar_item_key: cost
  output_element_key: cost_targets
- id: 99
  general_sub_header: maximum increase
  key: policy_cost_electricity
  position: 2
  sidebar_item_key: cost
  output_element_key: cost_targets
