---
- id: 197
  key: flexibility_merit_order_merit_order_price
  position: 4
  sidebar_item_key: data_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- id: 214
  key: data_export_application_demands
  position: 2
  sidebar_item_key: data_export
  output_element_key: use_of_primary_energy
- id: 215
  key: data_export_production
  position: 3
  sidebar_item_key: data_export
  output_element_key: investment_table
- id: 218
  key: data_export_energy_flows
  position: 1
  sidebar_item_key: data_export
  output_element_key: sankey
- id: 248
  key: data_export_household_heat
  position: 5
  sidebar_item_key: data_export
  output_element_key: household_heat_demand_and_production
- id: 258
  key: data_export_hydrogen
  position: 7
  sidebar_item_key: data_export
  output_element_key: hydrogen_demand
- id: 271
  key: data_export_network_gas
  position: 6
  sidebar_item_key: data_export
  output_element_key: network_gas_demand
- id: 276
  key: data_export_heat_network
  position: 8
  sidebar_item_key: data_export
  output_element_key: heat_network_demand
