---
- key: data_export_overview
  position: 1
  sidebar_item_key: data_export
  output_element_key: sankey
- key: data_export_energy_flows
  position: 2
  sidebar_item_key: data_export
  output_element_key: sankey
- key: data_export_molecule_flows
  position: 3
  sidebar_item_key: data_export
  output_element_key: co2_emissions
- key: data_export_application_demands
  position: 4
  sidebar_item_key: data_export
  output_element_key: use_of_primary_energy
- key: data_export_production
  position: 5
  sidebar_item_key: data_export
  output_element_key: costs_overview_detailed
- key: data_export_costs
  position: 6
  sidebar_item_key: data_export
  output_element_key: costs_overview_detailed
- key: data_export_household_heat
  position: 7
  sidebar_item_key: data_export
  output_element_key: household_heat_demand_and_production
- key: data_export_hydrogen
  position: 8
  sidebar_item_key: data_export
  output_element_key: hydrogen_demand
- key: data_export_network_gas
  position: 9
  sidebar_item_key: data_export
  output_element_key: network_gas_demand
- key: data_export_heat_network
  position: 10
  sidebar_item_key: data_export
  output_element_key: heat_network_demand
- key: data_export_agriculture_heat
  position: 11
  sidebar_item_key: data_export
  # output_element_key: agriculture_heat_demand
- key: flexibility_merit_order_merit_order_price
  position: 12
  sidebar_item_key: data_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: data_export_residual_load_curves
  position: 13
  sidebar_item_key: data_export
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance
