---
- id: 238
  key: costs_imported_electricity
  position: 0
  sidebar_item_key: electricity_import_costs
  alt_output_element_key: breakdown_electricity_costs
  output_element_key: merit_order_price_curve
