---
- id: 154
  key: costs_employment
  position: 1
  dependent_on: _always_hidden
  sidebar_item_key: employment
  alt_output_element_key: employment_categories
  output_element_key: employment_categories
