---
- key: flexibility_electricity_storage_overview
  position: 50
  sidebar_item_key: flexibility_storage
  output_element_key: hourly_flexibility_electricity
- key: flexibility_power_storage_households_flexibility_p2p_electricity
  position: 100
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- key: flexibility_power_storage_transport_car_flexibility_p2p_electricity
  position: 200
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- general_sub_header: electricity_input
  key: flexibility_power_storage_energy_flexibility_mv_batteries_electricity
  position: 300
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- general_sub_header: electricity_input
  key: flexibility_power_storage_energy_flexibility_pumped_storage_electricity
  dependent_on: has_mountains
  position: 400
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- general_sub_header: electricity_input
  key: flexibility_power_storage_energy_flexibility_hv_opac_electricity
  position: 500
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- general_sub_header: electricity_input
  key: flexibility_power_storage_energy_flexibility_flow_batteries_electricity
  position: 550
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- key: flexibility_power_storage_wind_turbine_inland
  position: 600
  sidebar_item_key: flexibility_storage
  output_element_key: flexibility_hourly_battery_wind
- key: flexibility_power_storage_solar_pv_solar_radiation
  position: 700
  sidebar_item_key: flexibility_storage
  output_element_key: flexibility_hourly_battery_solar

- key: flexibility_power_storage_forecast_order
  position: 100
  sidebar_item_key: flexibility_forecast_storage_order
  output_element_key: storage_specifications
