---
- key: flexibility_flexibility_net_load
  position: 1
  sidebar_item_key: flexibility_net_load
  alt_output_element_key: electricity_network_load
  output_element_key: electricity_network_capacity_and_peaks
- key: flexibility_flexibility_demand_response_ev
  position: 10
  sidebar_item_key: flexibility_net_load
  output_element_key: dynamic_demand_curve
- key: flexibility_flexibility_demand_response_hhp
  position: 11
  sidebar_item_key: flexibility_net_load
  output_element_key: household_network_gas_hhp_cop_cost
- key: flexibility_flexibility_solar_pv_curtailment
  position: 2
  sidebar_item_key: flexibility_net_load
  output_element_key: hourly_solar_pv_curtailment
- key: flexibility_flexibility_demand_response_load_shifting
  position: 5
  sidebar_item_key: flexibility_net_load
  output_element_key: merit_order_hourly_flexibility
- key: flexibility_flexibility_hybrid_offshore_wind
  position: 3
  sidebar_item_key: flexibility_net_load
  output_element_key: installed_hybrid_offshore_capacities
  