---
- id: 168
  key: flexibility_flexibility_power_to_gas
  position: 1
  sidebar_item_key: flexibility_conversion
  alt_output_element_key: use_of_excess_electricity
  output_element_key: use_of_excess_electricity
- id: 225
  key: flexibility_flexibility_power_to_kerosene
  position: 4
  sidebar_item_key: flexibility_conversion
  alt_output_element_key: kerosene_production_in_bunkers
  output_element_key: carbon_balance
- id: 272
  key: flexibility_flexibility_power_to_heat_for_industry
  position: 3
  sidebar_item_key: flexibility_conversion
  output_element_key: use_of_excess_electricity
- id: 285
  general_sub_header: heat_output
  key: flexibility_flexibility_power_to_heat_for_district_heating
  position: 2
  sidebar_item_key: flexibility_conversion
  output_element_key: use_of_excess_electricity
