---
- general_sub_header: price
  key: costs_combustion_fuel
  position: 1
  sidebar_item_key: fuel_costs
  output_element_key: costs_overview_detailed
- general_sub_header: change
  key: costs_nuclear_fuel
  position: 1
  sidebar_item_key: fuel_costs
  output_element_key: costs_overview_detailed
- general_sub_header: price
  key: costs_bio_fuel
  position: 2
  sidebar_item_key: fuel_costs
  output_element_key: greengas_costs
