---
- key: supply_heat_sources_mt
  position: 1
  sidebar_item_key: heat_mt
  output_element_key: sankey_heat_networks
- key: supply_heat_storage_mt
  position: 2
  sidebar_item_key: heat_mt
  output_element_key: heat_network_storage_mt
- key: supply_heat_transport_mt
  position: 3
  sidebar_item_key: heat_mt
  output_element_key: sankey_heat_networks
- key: supply_heat_network_order_mt
  position: 4
  sidebar_item_key: heat_mt
  output_element_key: heat_cost_capacity_mt
