---
- key: supply_heat_sources_ht
  position: 1
  sidebar_item_key: heat_ht
  output_element_key: sankey_heat_networks
- key: supply_heat_storage_ht
  position: 2
  sidebar_item_key: heat_ht
  output_element_key: heat_network_storage_ht
- key: supply_heat_transport_ht
  position: 3
  sidebar_item_key: heat_ht
  output_element_key: sankey_heat_networks
- key: supply_heat_network_order_ht
  position: 4
  sidebar_item_key: heat_ht
  output_element_key: heat_cost_capacity_ht
