---
- image: house_insulation.gif
  general_sub_header: heat_demand_reduction
  subheader_image: households_insulation_energy_label.png
  subheader_image_dependent_on_country: nl
  key: demand_households_insulation
  position: 4
  sidebar_item_key: households
  alt_output_element_key: effect_of_insulation_in_households
  output_element_key: effect_of_insulation_in_households
- image: house_lighting.gif
  general_sub_header: share
  key: demand_households_lighting
  position: 12
  sidebar_item_key: households
  alt_output_element_key: use_of_final_electricity_demand_in_households
  output_element_key: use_of_final_electricity_demand_in_households
- image: house_appliances.gif
  general_sub_header: change
  group_sub_header: change
  subheader_image: energy_label.png
  key: demand_households_appliances
  position: 11
  sidebar_item_key: households
  alt_output_element_key: use_of_final_electricity_demand_in_households
  output_element_key: use_of_final_electricity_demand_in_households
- image: house_heating.gif
  key: demand_households_heating
  group_sub_header: share
  position: 5
  sidebar_item_key: households
  alt_output_element_key: source_of_heat_used_in_households
  output_element_key: source_of_heat_used_in_households
- image: house.gif
  group_sub_header: "%/year"
  key: demand_households_demand_growth
  position: 13
  sidebar_item_key: households
  alt_output_element_key: households_final_demand_per_application
  output_element_key: households_final_demand_per_application
- image: house_heating.gif
  general_sub_header: share
  key: demand_households_cooling
  position: 9
  sidebar_item_key: households
  alt_output_element_key: source_of_cooling_in_households
  output_element_key: source_of_cooling_in_households
- image: house_heating.gif
  general_sub_header: share
  key: demand_households_cooking
  position: 10
  sidebar_item_key: households
  alt_output_element_key: source_of_cooking_in_households
  output_element_key: source_of_cooking_in_households
- image: house_heating.gif
  general_sub_header: change
  key: demand_households_behaviour
  position: 14
  sidebar_item_key: households
  alt_output_element_key: households_final_demand_per_application
  output_element_key: households_final_demand_per_application
- image: house.gif
  general_sub_header: number
  key: demand_households_population
  position: 2
  sidebar_item_key: households
  alt_output_element_key: population_residences_overview
  output_element_key: households_final_demand_per_application
