---
- id: 176
  image: industry.gif
  general_sub_header: "%/year"
  key: demand_industry_chemical_demand_growth
  position: 1
  sidebar_item_key: industry_chemical
  alt_output_element_key: use_of_final_demand_in_industry_chemical_detailed
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
- id: 177
  image: industry.gif
  general_sub_header: "%/year"
  key: demand_industry_chemical_efficiency_improvement
  position: 2
  sidebar_item_key: industry_chemical
  alt_output_element_key: use_of_final_demand_in_industry_chemical_detailed
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
- id: 178
  image: industry.gif
  general_sub_header: share
  key: demand_industry_chemical_heat
  position: 3
  sidebar_item_key: industry_chemical
