---
- id: 265
  key: introduction_to_etm
  position: 1
  sidebar_item_key: introduction
  output_element_key: workflow
- id: 266
  key: overview_final_demand
  position: 3
  sidebar_item_key: introduction
  output_element_key: final_energy_demand_per_sector_joule
- id: 267
  key: overview_co2_emissions
  position: 2
  sidebar_item_key: introduction
  output_element_key: co2_emissions
