---
- key: scenario_overview
  position: 5
  sidebar_item_key: introduction
  output_element_key: sankey_energy_overview
- key: demand
  position: 10
  sidebar_item_key: introduction
  output_element_key: final_energy_demand_per_sector_joule
- key: supply
  position: 15
  sidebar_item_key: introduction
  output_element_key: source_of_electricity_production
- key: emissions
  position: 20
  sidebar_item_key: introduction
  output_element_key: emissions
- key: costs
  position: 25
  sidebar_item_key: introduction
  output_element_key: costs_overview
