---
- id: 19
  general_sub_header: change
  key: costs_nuclear_investment
  position: 2
  sidebar_item_key: nuclear
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
- id: 20
  general_sub_header: change
  key: costs_nuclear_operational_and_maintenance
  position: 3
  sidebar_item_key: nuclear
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
