---
- id: 32
  general_sub_header: "%/year"
  key: demand_other_demand_growth
  position: 1
  sidebar_item_key: other
  alt_output_element_key: use_of_final_demand_in_other_sector
  output_element_key: use_of_final_demand_in_other_sector
