---
- key: flexibility_security_of_supply_electricity
  position: 1
  sidebar_item_key: security_of_supply
  alt_output_element_key: merit_order
  output_element_key: merit_order_hourly_supply
- key: flexibility_security_of_supply_heat
  position: 2
  sidebar_item_key: security_of_supply
  alt_output_element_key: heat_network_demand
  output_element_key: flexibility_hourly_heat_network_supply_demand