---
- id: 17
  general_sub_header: change
  key: costs_solar_investment
  position: 1
  sidebar_item_key: solar
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
- id: 500
  image: ''
  general_sub_header: ''
  key: technology_solar_panels
  position: 2
  dependent_on: ''
  sidebar_item_key: solar
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
