---
- key: specs_electricity_renewable_wind_turbines
  position: 1
  sidebar_item_key: specs_renewable_electricity
  output_element_key: merit_order
- key: specs_electricity_renewable_hydro_electric
  position: 3
  sidebar_item_key: specs_renewable_electricity
  output_element_key: merit_order
- key: specs_electricity_renewable_solar_power
  position: 2
  sidebar_item_key: specs_renewable_electricity
  output_element_key: merit_order
- key: specs_electricity_renewable_waste_power
  position: 5
  sidebar_item_key: specs_renewable_electricity
  output_element_key: merit_order
- key: specs_electricity_renewable_hydrogen_plants
  position: 6
  sidebar_item_key: specs_renewable_electricity
  output_element_key: merit_order
- key: specs_electricity_renewable_biomass_plants
  position: 4
  sidebar_item_key: specs_renewable_electricity
  output_element_key: merit_order
