---
- key: specs_electricity_coal_plants
  position: 1
  sidebar_item_key: specs_electricity
  output_element_key: costs_overview_detailed
- key: specs_electricity_gas_plants
  position: 2
  sidebar_item_key: specs_electricity
  output_element_key: costs_overview_detailed
- key: specs_electricity_oil_plants
  position: 3
  sidebar_item_key: specs_electricity
  output_element_key: costs_overview_detailed
- key: specs_electricity_nuclear_plant
  position: 4
  sidebar_item_key: specs_electricity
  alt_output_element_key: source_of_electricity_production
  output_element_key: costs_overview_detailed
- key: costs_imported_electricity
  position: 5
  sidebar_item_key: specs_electricity
  output_element_key: merit_order_price_curve
