---
- id: 38
  general_sub_header: change
  key: policy_sustainability_co2_emission_compared_to_1990
  position: 1
  sidebar_item_key: sustainability
  alt_output_element_key: co2_emissions
  output_element_key: renewability_targets
- id: 39
  general_sub_header: "% of total"
  key: policy_sustainability_renewables
  position: 2
  sidebar_item_key: sustainability
  output_element_key: renewability_targets
