---
- general_sub_header: share
  key: demand_transport_marine_fuels
  position: 4
  sidebar_item_key: transport_fuels
  alt_output_element_key: use_of_transport_fuels
  output_element_key: use_of_transport_fuels
- general_sub_header: share
  key: demand_transport_trains
  position: 2
  sidebar_item_key: transport_fuels
  alt_output_element_key: use_of_transport_fuels
  output_element_key: use_of_transport_fuels
- general_sub_header: share
  key: demand_transport_road_transport
  position: 1
  sidebar_item_key: transport_fuels
  alt_output_element_key: use_of_transport_fuels
  output_element_key: use_of_transport_fuels
- general_sub_header: share
  key: demand_transport_international_aviation
  position: 5
  sidebar_item_key: transport_fuels
  output_element_key: co2_emission_international_transportation
- key: demand_transport_international_shipping
  position: 6
  sidebar_item_key: transport_fuels
  alt_output_element_key: refinery
  output_element_key: co2_emission_international_transportation
