---
- id: 219
  general_sub_header: of_total
  key: demand_transport_international_transport
  position: 1
  sidebar_item_key: transport_international_transport
  alt_output_element_key: use_of_final_demand_in_international_transport
  output_element_key: international_transport_categories_overview
- id: 222
  general_sub_header: year
  key: demand_transport_international_transport_mobility_growth
  position: 2
  sidebar_item_key: transport_international_transport
  alt_output_element_key: use_of_final_demand_in_international_transport
  output_element_key: international_transport_categories_overview
- id: 223
  general_sub_header: share
  key: demand_transport_international_navigation_technology
  position: 4
  sidebar_item_key: transport_international_transport
  alt_output_element_key: co2_emission_international_transportation
  output_element_key: use_of_final_demand_in_international_transport
- id: 224
  key: demand_transport_international_aviation_technology
  position: 3
  sidebar_item_key: transport_international_transport
  output_element_key: use_of_final_demand_in_international_transport
