---
- id: 9
  general_sub_header: change
  key: costs_wind_investment
  position: 1
  sidebar_item_key: wind
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
- id: 10
  general_sub_header: change
  key: costs_wind_operational_and_maintenance
  position: 2
  sidebar_item_key: wind
  alt_output_element_key: overview_costs_of_electricity_production
  output_element_key: overview_costs_of_electricity_production
