---
- under_construction: false
  unit: MT
  percentage: false
  group: ccus
  sub_group:
  show_point_label: false
  growth_chart: false
  key: mekko_of_co2_demand_supply
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: mekko
- under_construction: false
  unit: MT
  percentage: false
  group: ccus
  sub_group:
  show_point_label: false
  growth_chart: false
  key: ccus_sankey
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: sankey
- under_construction: false
  unit: MJ
  percentage: false
  group: ccus
  sub_group:
  show_point_label: false
  growth_chart: false
  key: energy_use_of_ccus
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: T
  percentage: false
  group: ccus
  sub_group:
  show_point_label: false
  growth_chart: false
  key: co2_sankey
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: sankey
- under_construction: false
  unit: MJ
  percentage: false
  group: ccus
  sub_group:
  show_point_label: false
  growth_chart: false
  key: use_of_coal_gases
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
