---
- under_construction: false
  unit:
  percentage:
  group: Cost
  sub_group:
  show_point_label:
  growth_chart:
  key: overview_costs_of_electricity_production
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  output_element_type_name: block
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: additional_infrastructure_investments
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: use_network_calculations
  output_element_type_name: waterfall
- under_construction: false
  unit: bln_euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: investment_table
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: html_table
- under_construction: false
  unit: Eur/Mwh
  percentage: false
  group: Cost
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: greengas_costs
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: heat_infrastructure_ht_annualised_costs
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: heat_infrastructure_mt_annualised_costs
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: heat_infrastructure_lt_annualised_costs
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: heat_infrastructure_annualised_costs_per_household_ht
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: "â‚¬/MJ heat"
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: household_network_gas_hhp_cop_cost
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: hhp_cop_cost
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: costs_overview
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group:
  show_point_label: false
  growth_chart: false
  key: costs_overview_detailed
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: vertical_stacked_bar
