---
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: use_of_final_electricity_demand_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: source_of_electricity_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: source_of_heat_used_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
  related_output_element_key: household_heat_demand_and_production
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: true
  key: effect_of_insulation_in_households
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
  related_output_element_key: household_heat_demand_and_production
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: source_of_cooling_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: source_of_cooking_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: ''
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: population_residences_overview
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: html_table
- under_construction: false
  unit: MW
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: household_heat_demand_and_production
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: heat_demand_and_production
- under_construction: false
  unit: MW
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: household_space_heater_hhp_hourly_demand
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: demand_curve
- under_construction: false
  unit: ''
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: hybrid_heat_pump
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: html_table
- under_construction: false
  unit: km2
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: roof_area_for_pv_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: '#'
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: true
  key: number_of_residences_overview
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: mekko
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: residential_heating_demand
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: category_bar
  config:
    show_total_row: false
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: true
  key: use_of_final_demand_in_households
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: has_buildings
  output_element_type_name: bezier
- under_construction: false
  unit:
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: households_deficits
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: true
  dependent_on:
  output_element_type_name: html_table
- under_construction: false
  unit: number
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: false
  key: residential_heating_technologies
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: category_bar
  config:
    show_total_row: false
