---
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: source_of_heat_and_electricity_in_industry
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: true
  key: use_of_final_demand_in_industry_aluminium
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: true
  key: use_of_final_demand_in_industry_other_metals
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: MJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: true
  key: demand_in_industry_steel
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: true
  key: use_of_final_demand_in_industry_chemical_detailed
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: mekko_of_detailed_final_demand_in_industry
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  output_element_type_name: mekko
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: mekko_of_detailed_final_demand_in_industry_energetic
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  output_element_type_name: mekko
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_chemical_refineries
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_other_paper
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_chemical_other
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_other_food
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_chemical_fertilizers
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_other
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: industry
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_industry_other_ict
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
