---
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: true
  key: use_of_final_demand_in_international_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: MT
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: co2_emission_international_transportation
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: transport_categories_overview
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_passenger_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_cars
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_motorcycles_and_bicycles
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_planes
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_busses_trains_and_trams
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_freight_transport_technologies
  max_axis_value: 
  min_axis_value: 
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: MJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_freight_shipping_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: MJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_freight_train_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: MJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_freight_truck_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: MJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_freight_van_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: use_of_final_demand_in_freight_transport
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: transport
  show_point_label: false
  growth_chart: false
  key: international_transport_categories_overview
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
