---
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: agriculture
  show_point_label: false
  growth_chart: true
  key: use_of_final_demand_in_agriculture
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: has_agriculture
  output_element_type_name: bezier
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: agriculture
  show_point_label: false
  growth_chart: false
  key: source_of_heat_in_agriculture
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: has_agriculture
  output_element_type_name: bezier
- under_construction: false
  unit: MJ
  percentage: false
  group: Demand
  sub_group: agriculture
  show_point_label: false
  growth_chart: false
  key: agriculture_local_heat_mekko
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: 
  description: 
  output_element_type_name: mekko
