---
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: electricity_network_load
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: electricity_lv_network_load
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: electricity_mv_network_load
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: electricity_hv_network_load
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: lv_demand_curves
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: demand_curve
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: mv_demand_curves
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: hourly_stacked_area
- under_construction: false
  unit: MW
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: hv_demand_curves
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: hourly_stacked_area
- under_construction: false
  unit: ''
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: electricity_network_capacity_and_peaks
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: use_network_calculations
  output_element_type_name: html_table
  related_output_element_key: electricity_network_load
- under_construction: false
  unit: PJ
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: sankey_hybrid_offshore
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: sankey
- under_construction: false
  unit: ''
  percentage: false
  group: Network
  sub_group: ''
  show_point_label: false
  growth_chart: false
  key: capacity_energy_hybrid_offshore
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: html_table
