---
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label: true
  growth_chart: false
  key: use_of_primary_energy
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: MT
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: co2_emissions
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: "%"
  percentage: false
  group: Overview
  show_point_label: true
  growth_chart:
  key: renewability
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label:
  growth_chart:
  key: mekko_of_primary_demand
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  output_element_type_name: mekko
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: source_of_electricity_production
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
  related_output_element_key: merit_order_hourly_supply
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: sankey_energy_overview
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: sankey
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: sankey_2010
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: sankey
- under_construction: false
  unit: "%"
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: relative_primary_co2
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: "%"
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: relative_primary_demand_of_coal_oil_and_gas
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: final_demand_mekko_energetic_mece
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: mekko
  related_output_element_key: dynamic_demand_curve
- under_construction: false
  unit: PJ
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: final_energy_demand_per_sector_joule
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: bezier
- under_construction: false
  unit:
  percentage: false
  group: Overview
  show_point_label: false
  growth_chart: false
  key: workflow
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: html_table
  config:
    supports_to_image: false
- under_construction: false
  unit: TWh
  percentage: false
  group: Overview
  show_point_label:
  growth_chart:
  key: mekko_of_storage_volume
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  output_element_type_name: mekko
