---
- under_construction: false
  unit: MW
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: security_of_supply
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: MT
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: co2_of_electricity_production
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: "%"
  percentage: true
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: renewable_electricity
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: ''
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: merit_order_table
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: has_merit_order
  output_element_type_name: html_table
- under_construction: false
  unit: Eur/Mwh
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: merit_order
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: has_merit_order
  output_element_type_name: cost_capacity_bar
- under_construction: false
  unit: EUR/MWh
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: merit_order_price_curve
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: MW
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: merit_order_hourly_supply
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: ''
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: merit_order_excess_events
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: d3
- under_construction: false
  unit: MW
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: dynamic_demand_curve
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: demand_curve
- under_construction: false
  unit: PJ
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: sankey_electrical_interconnection
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  description:
  output_element_type_name: sankey
- under_construction: false
  unit: MW
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: supply_offshore_solar_wind
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: true
  dependent_on: ''
  output_element_type_name: hourly_stacked_area
- under_construction: false
  unit: PJ
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: mekko_of_electricity_network
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: mekko
- under_construction: false
  unit:
  percentage: false
  group: Supply
  sub_group: electricity
  show_point_label: false
  growth_chart: false
  key: power_shortage
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on:
  output_element_type_name: html_table
