---
- under_construction: false
  unit: PJ
  percentage: false
  group: Supply
  sub_group: transport_fuels
  show_point_label: false
  growth_chart: false
  key: use_of_transport_fuels
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: PJ
  percentage: false
  group: Supply
  sub_group: transport_fuels
  show_point_label: false
  growth_chart: false
  key: liquid_fuels
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: sankey
- under_construction: false
  unit: MJ
  percentage: false
  group: Supply
  sub_group: transport_fuels
  show_point_label: false
  growth_chart: false
  key: mekko_of_kerosene_demand_supply
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: mekko