---
- under_construction: false
  unit: PJ
  percentage: false
  group: Supply
  sub_group: production_curves_and_import
  show_point_label: true
  growth_chart: false
  key: future_energy_imports
  max_axis_value: 
  min_axis_value: 
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: waterfall
- under_construction: false
  unit: PJ
  percentage: false
  group: Supply
  sub_group: production_curves_and_import
  show_point_label: true
  growth_chart: false
  key: present_energy_imports
  max_axis_value: 
  min_axis_value: 
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: waterfall

