development: &DEV
    # base url for api requests. This is used when CORS is enabled
    # (which is the default) or when the rails application runs a
    # local rack-based AJAX proxy
    api_url: http://beta.et-engine.com

    # URL for the ETLoader application. ETLoader and testing ground features are
    # presently supported only when "api_url" is "http://beta.et-engine.com".
    etloader_url: http://ivy.et-engine.com

    # This sets the url we use as API proxy. The proxying is handled
    # by nginx or a local rack-based proxy
    api_proxy_url: /ete_proxy

    # base url for partners api. This is used to retrieve the partner
    # names and such that are visible in the footer.
    partners_url: http://et-model.com

    # google analytics key
    ga_tracker_code: 123456

    #  standalone instances are those such as the laptop. If set to true
    # the remote links and scripts will be disabled and the videos will
    # be played with a local player rather than vimeo/youtube. CORS will be
    # disabled, too
    standalone: false

    # URL that shows the gquery details (used on the charts admin page)
    # the gquery key is appended to the url
    gquery_detail_url: http://et-engine.com/data/latest/gqueries/key/

    # set to true if you want a "production server" warning in the admin section
    live_server: false

    # optional URL overrides for the splash screen links
    # mixer_url: http://mixer.et-model.com
    # etflex_url: http://light.et-model.com

    # Optionally send error messages to the Airbrake service by providing your
    # API key:
    airbrake_api_key: false
production: &PRODUCTION
    <<: *DEV
test:
    <<: *DEV
    # set to true to pipe requests through the local proxy
    standalone: true
    etloader_url: http://localhost:3002
staging:
    <<: *PRODUCTION
