# Find more details about this configuration file at http://github.com/fnando/i18n-js
translations:
  - file: "public/javascripts/i18n/%{locale}.js"
    only:
      - '*.areas.*'
      - '*.units.*'
      - '*.output_element_series.*'
      - '*.dashboard.costs.*'
      - '*.unit_conversions.*'
      - '*.report.*'
      - '*.output_elements.common'
      - '*.output_elements.empty'
      - '*.output_elements.block_chart'
      - '*.output_elements.cost_capacity_chart'
      - '*.output_elements.hydrogen_cost_capacity_chart'
      - '*.output_elements.merit_excess_chart'
      - '*.output_elements.tables.merit_order'
      - '*.output_elements.storage_chart'
      - '*.output_elements.cwe_chart'
      - '*.output_elements.import_export_capacity_chart'
      - '*.output_elements.import_export_renewables_chart'
      - '*.output_elements.sankey_labels'
      - '*.output_elements.flexibility_order'
      - '*.output_elements.forecast_storage_order.*'
      - '*.output_elements.heat_network_order'
      - '*.output_elements.households_space_heating_producer_order.*'
      - '*.output_elements.hhp_cop_cost.*'
      - '*.input_elements.common'
      - '*.radio_elements.*'
      - '*.dashboard_items.co2_reduction.*'
      - '*.dashboard_items.greenhouse_gas.*'
      - '*.toggle.*'
      - '*.simple_form.*'
      - '*.wells.*'
      - '*.local_global.*'
      - '*.energy_mix.*'
      - '*.establishment_shot.*'
      - '*.results_tip.*'
      - '*.custom_curves.*'
      - '*.date.*'
      - '*.meta.name'
      - '*.scenario.created_with'
      - '*.toast.*'
      - '*.scenario_nav.*'
      - '*.node_details.*'
      - '*.chart_picker.*'
      - '*.survey.*'
      - '*.export.esdl.*'
      - '*.period.*'
