# Find more details about this configuration file at http://github.com/fnando/i18n-js
translations:
  - file: "public/javascripts/i18n/translations.js"
    only:
      - '*.units.*'
      - '*.output_element_series.*'
      - '*.dashboard.costs.*'
      - '*.unit_conversions.*'
      - '*.targets.*'
      - '*.output_elements.common'
      - '*.output_elements.empty'
      - '*.output_elements.block_chart'
      - '*.output_elements.merit_order_chart'
      - '*.output_elements.merit_excess_chart'
      - '*.output_elements.tables.merit_order'
      - '*.output_elements.storage_chart'
      - '*.output_elements.cwe_chart'
      - '*.output_elements.import_export_capacity_chart'
      - '*.output_elements.import_export_renewables_chart'
      - '*.output_elements.sankey_labels'
      - '*.input_elements.common'
      - '*.constraints.co2_reduction.*'
      - '*.constraints.greenhouse_gas.*'
      - '*.fce_toggle.*'
      - '*.simple_form.*'
      - '*.wells.*'
