warmte:
  zonthermie:
    collectief: factsheet_supply_heat_from_solar_thermal_collective
    individueel: factsheet_supply_heat_from_solar_thermal_individual
    totaal: factsheet_supply_heat_from_solar_thermal

  omgevingswarmte:
    collectief : factsheet_supply_heat_from_ambient_collective
    individueel: factsheet_supply_heat_from_ambient_individual
    totaal: factsheet_supply_heat_from_ambient_total

  restwarmte:
    collectief : factsheet_supply_heat_from_rest_collective
    industrieel: factsheet_supply_heat_from_rest_industry
    totaal: factsheet_supply_heat_from_rest

  geothermie:
    collectief: factsheet_supply_heat_from_geothermal_collective
    totaal: factsheet_supply_heat_from_geothermal_collective

gassen:
  aardgas:
    individueel: factsheet_demand_gas_from_fossil_individual
    collectief: factsheet_demand_gas_from_fossil_collective
    industrie: factsheet_demand_gas_from_fossil_industry
    mobiliteit: factsheet_demand_gas_from_fossil_transport
    elektriciteit en overig: factsheet_demand_gas_from_fossil_electricity_other
    totaal: factsheet_supply_gas_from_fossil

  groen_gas_biogas:
    individueel: factsheet_demand_gas_from_biogas_greengas_individual
    collectief: factsheet_demand_gas_from_biogas_greengas_collective
    industrie: factsheet_demand_gas_from_biogas_greengas_industry
    mobiliteit: factsheet_demand_gas_from_biogas_greengas_transport
    elektriciteit en overig: factsheet_demand_gas_from_biogas_greengas_electricity_other
    totaal: factsheet_supply_gas_from_biogas

  waterstof_vraag:
    individueel: factsheet_demand_hydrogen_in_individual_heat
    collectief: factsheet_demand_hydrogen_in_collective_heat
    industrie: factsheet_demand_hydrogen_in_industry
    mobiliteit: factsheet_demand_hydrogen_in_transport
    elektriciteit: factsheet_demand_hydrogen_in_electricity
    transportverliezen: factsheet_demand_hydrogen_distribution_losses
    export: factsheet_demand_hydrogen_exported

  waterstof_productie:
    import: factsheet_supply_hydrogen_imported
    lokaal geproduceerd: factsheet_supply_hydrogen_locally_produced

elektriciteit:
  aanbod:
    aantal_windturbines_land_3MW: factsheet_number_of_wind_turbine_inland_coastal
    vollasturen_windturbines_land_3MW: merit_order_onshore_wind_turbines_full_load_hours_in_merit_order_table
    aantal_windturbines_zee_10MW: factsheet_number_of_wind_turbines_offshore
    vollasturen_windturbines_zee_10MW: merit_order_offshore_wind_turbines_full_load_hours_in_merit_order_table
    opbrengst_uit_wind: factsheet_supply_from_wind_and_other_electricity
    aantal_panelen_zon_op_dak: factsheet_number_of_roof_solar_pv
    opbrengst_zon_pv_huishoudens: factsheet_supply_electricity_from_roof_solar_households
    opbrengst_zon_pv_gebouwen: factsheet_supply_electricity_from_roof_solar_buildings
    opbrengst_zon_pv_op_land: factsheet_supply_from_solar_pv_plants
    hectare_zonneveld: factsheet_solar_pv_plants_land_use
    totale_capaciteit_zon_pv: factsheet_installed_capacity_of_solar_pv

  vraag:
    opwek_waterstof: factsheet_demand_electricity_of_production_of_hydrogen
    elektriciteit_overig: factsheet_demand_electricity_of_other
    elektriciteit_gebouwde_omgeving_ex_verwarming: factsheet_demand_electricity_of_built_environment_ex_heating
    elektriciteit_individueel_verwarmen: factsheet_demand_electricity_of_individual_heating
    elektriciteit_collectief_verwarmen : factsheet_demand_electricity_of_collective_heating
    elektriciteit_mobiliteit: factsheet_demand_electricity_of_transport
    elektriciteit_data_ICT : factsheet_demand_electricity_of_ict_data

  hernieuwbaarheids_percentage:
    share_solar_and_wind_in_total_electricity_mix: factsheet_share_solar_and_wind_in_electricity_production

biomassa:
  vraag:
    collectief: factsheet_demand_of_biomass_in_collective_heat_production
    individueel: factsheet_demand_of_biomass_in_individual_heat_production
    transport: factsheet_demand_of_biomass_transport
    industrie: factsheet_demand_of_biomass_industry
    elektriciteit: factsheet_demand_of_biomass_electricity
    overig_in_gebouwde_omgeving_(o.a.koken): factsheet_demand_of_biomass_other_built_environment

fossiel:
  vraag:
    warmte: factsheet_demand_fossil_in_households_buildings_agriculture
    industrie: factsheet_demand_fossil_in_industry
    mobiliteit: factsheet_demand_fossil_in_mobility
    elektriciteit: factsheet_demand_fossil_in_electricity
    totaal: factsheet_demand_fossil_in_total
