---
- key: costs_imported_heat
  share_group: ''
  step_value: 0.1
  draw_to_min:
  draw_to_max:
  unit: "â‚¬/GJ"
  fixed: false
  interface_group: ''
  command_type: ''
  related_converter: ''
  position: 8
  dependent_on: ''
  slide_key: costs_residual_heat
- key: costs_industry_residual_heat
  share_group: ''
  step_value: 0.1
  draw_to_min:
  draw_to_max:
  unit: "%"
  fixed: false
  interface_group: ''
  command_type: ''
  related_converter: ''
  position: 1
  dependent_on: ''
  slide_key: costs_residual_heat
