---
- key: efficiency_households_space_heater_combined_network_gas
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_combined_network_gas
  position: 5
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_combined_hydrogen
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_combined_hydrogen
  position: 6
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_heatpump_ground_water_electricity
  interface_group: efficiency_households
  step_value: 1.0
  unit: "COP"
  related_node: households_space_heater_heatpump_ground_water_electricity
  position: 7
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_wood_pellets
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_wood_pellets
  position: 8
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_electricity
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_electricity
  position: 9
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_network_gas
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_network_gas
  position: 10
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_heatpump_air_water_electricity
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_heatpump_air_water_electricity
  position: 11
  slide_key: costs_heat_built_environment
- key: efficiency_households_space_heater_hybrid_heatpump_air_water_electricity
  interface_group: efficiency_households
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_hybrid_heatpump_air_water_electricity
  position: 12
  slide_key: costs_heat_built_environment
- key: efficiency_buildings_space_heater_collective_heatpump_water_water_ts_electricity
  interface_group: efficiency_buildings
  step_value: 1.0
  unit: "COP"
  related_node: buildings_space_heater_collective_heatpump_water_water_ts_electricity
  position: 20
  slide_key: costs_heat_built_environment
- key: efficiency_buildings_space_heater_network_gas
  interface_group: efficiency_buildings
  step_value: 1.0
  unit: "%"
  related_node: buildings_space_heater_network_gas
  position: 21
  slide_key: costs_heat_built_environment
- key: efficiency_buildings_space_heater_combined_hydrogen
  interface_group: efficiency_buildings
  step_value: 1.0
  unit: "%"
  related_node: buildings_space_heater_combined_hydrogen
  position: 22
  slide_key: costs_heat_built_environment
- key: efficiency_buildings_space_heater_electricity
  interface_group: efficiency_buildings
  step_value: 1.0
  unit: "%"
  related_node: buildings_space_heater_electricity
  position: 23
  slide_key: costs_heat_built_environment
- key: efficiency_buildings_space_heater_wood_pellets
  interface_group: efficiency_buildings
  step_value: 1.0
  unit: "%"
  related_node: buildings_space_heater_wood_pellets
  position: 24
  slide_key: costs_heat_built_environment