---
- key: investment_costs_combustion_gas_plant
  interface_group: costs
  step_value: 1.0
  unit: "%"
  command_type: value
  related_node: energy_power_combined_cycle_network_gas
  position: 1
  slide_key: specs_electricity_gas_plants
- key: om_costs_combustion_gas_plant
  interface_group: costs
  step_value: 1.0
  unit: "%"
  related_node: energy_power_combined_cycle_network_gas
  position: 2
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_combined_cycle_network_gas
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 3
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_turbine_network_gas
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 4
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_ultra_supercritical_network_gas
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 5
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_engine_network_gas
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 3
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_combined_cycle_network_gas
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 6
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_combined_cycle_network_gas_heat
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 7
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_local_engine_network_gas
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 8
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_local_engine_network_gas_heat
  interface_group: efficiency
  step_value: 1.0
  unit: "%"
  position: 9
  slide_key: specs_electricity_gas_plants