---
- key: om_costs_co2_ccs
  step_value: 1.0
  unit: "%"
  position: 2
  slide_key: costs_co2_capture_energy
- key: investment_costs_co2_ccs
  step_value: 1.0
  unit: "%"
  position: 1
  slide_key: costs_co2_capture_energy