---
- key: investment_costs_solar_solar_panels
  step_value: 1.0
  unit: "%"
  related_node: households_solar_pv_solar_radiation
  position: 1
  slide_key: costs_solar_investment
- key: investment_costs_solar_concentrated_solar_power
  step_value: 1.0
  unit: "%"
  position: 2
  dependent_on: has_solar_csp
  slide_key: costs_solar_investment
