---
- key: industry_useful_demand_for_chemical_other
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_chemical_other
- key: industry_useful_demand_for_chemical_other_electricity_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 2
  slide_key: demand_industry_chemical_other
- key: industry_useful_demand_for_chemical_other_useable_heat_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 3
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_burner_network_gas_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_burner_network_gas
  position: 4
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_burner_crude_oil_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_burner_crude_oil
  position: 5
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_burner_wood_pellets_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_burner_wood_pellets
  position: 7
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_burner_coal_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_burner_coal
  position: 6
  slide_key: demand_industry_chemical_other
- key: industry_final_demand_for_chemical_other_steam_hot_water_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  position: 13
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_steam_recompression_electricity_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_steam_recompression_electricity
  position: 11
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_heatpump_water_water_electricity_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_heatpump_water_water_electricity
  position: 12
  slide_key: demand_industry_chemical_other
- key: capacity_of_industry_chemicals_other_flexibility_p2h_electricity
  step_value: 1.0
  unit: MW
  interface_group: hybrid_heating
  related_node: industry_chemicals_other_flexibility_p2h_network_gas_electricity
  position: 13
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_heater_electricity_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_heater_electricity
  position: 9
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_burner_hydrogen_share
  share_group: chemical_other_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_other_burner_hydrogen
  position: 8
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_wood_pellets_non_energetic_share
  share_group: chemical_other_non_energetic
  step_value: 0.1
  unit: "%"
  interface_group: chemical_other_non_energetic
  position: 14
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_hydrogen_non_energetic_share
  share_group: chemical_other_non_energetic
  step_value: 0.1
  unit: "%"
  interface_group: chemical_other_non_energetic
  position: 15
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_network_gas_non_energetic_share
  share_group: chemical_other_non_energetic
  step_value: 0.1
  unit: "%"
  interface_group: chemical_other_non_energetic
  position: 16
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_crude_oil_non_energetic_share
  share_group: chemical_other_non_energetic
  step_value: 0.1
  unit: "%"
  interface_group: chemical_other_non_energetic
  position: 17
  slide_key: demand_industry_chemical_other
- key: industry_chemicals_other_coal_non_energetic_share
  share_group: chemical_other_non_energetic
  step_value: 0.1
  unit: "%"
  interface_group: chemical_other_non_energetic
  position: 18
  slide_key: demand_industry_chemical_other
