---
- key: buildings_lighting_standard_fluorescent_electricity_share
  share_group: lighting_buildings
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_buildings_lighting
- key: buildings_lighting_efficient_fluorescent_electricity_share
  share_group: lighting_buildings
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_buildings_lighting
- key: buildings_lighting_led_electricity_share
  share_group: lighting_buildings
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: demand_buildings_lighting
