---
- key: industry_useful_demand_for_chemical_fertilizers
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_chemical_fertilizers
- key: industry_useful_demand_for_chemical_fertilizers_electricity_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 40
  slide_key: demand_industry_chemical_fertilizers
- key: industry_useful_demand_for_chemical_fertilizers_useable_heat_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry
  position: 41
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_network_gas_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_network_gas
  position: 50
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_crude_oil_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_crude_oil
  position: 51
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_coal_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_coal
  position: 53
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_wood_pellets_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_wood_pellets
  position: 52
  slide_key: demand_industry_chemical_fertilizers
- key: industry_final_demand_for_chemical_fertilizers_steam_hot_water_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  position: 54
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_local_ammonia_local_hydrogen_share
  share_group: fertilizer_production_route
  step_value: 0.1
  unit: "%"
  interface_group: fertilizer_production_route
  position: 30
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_local_ammonia_central_hydrogen_share
  share_group: fertilizer_production_route
  step_value: 0.1
  unit: "%"
  interface_group: fertilizer_production_route
  position: 31
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_central_ammonia_share
  share_group: fertilizer_production_route
  step_value: 0.1
  unit: "%"
  interface_group: fertilizer_production_route
  position: 32
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_hydrogen_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_hydrogen
  position: 55
  slide_key: demand_industry_chemical_fertilizers
- key: capacity_of_industry_chemicals_fertilizers_flexibility_p2h_electricity
  step_value: 1.0
  unit: MW
  interface_group: hybrid_heating
  related_node: industry_chemicals_fertilizers_flexibility_p2h_network_gas_electricity
  position: 100
  slide_key: demand_industry_chemical_fertilizers
