---
- key: households_useful_demand_hot_water_share
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 100
  slide_key: demand_households_demand_growth
- key: households_useful_demand_electric_appliances
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 105
  slide_key: demand_households_demand_growth
- key: households_useful_demand_lighting
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 110
  slide_key: demand_households_demand_growth
- key: households_useful_demand_cooking_per_person
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 115
  slide_key: demand_households_demand_growth

- key: households_useful_demand_for_cooling
  step_value: 0.1
  unit: "%"
  interface_group: per household
  position: 200
  slide_key: demand_households_demand_growth
