---
- key: transport_vehicle_using_electricity_efficiency
  step_value: 0.1
  unit: "%"
  command_type: efficiency_improvement
  position: 1
  slide_key: demand_transport_efficiency_improvement
- key: transport_vehicle_combustion_engine_efficiency
  step_value: 0.1
  unit: "%"
  command_type: efficiency_improvement
  position: 4
  slide_key: demand_transport_efficiency_improvement
- key: transport_ships_efficiency
  step_value: 0.1
  unit: "%"
  position: 6
  slide_key: demand_transport_efficiency_improvement
- key: transport_planes_efficiency
  step_value: 0.1
  unit: "%"
  position: 7
  slide_key: demand_transport_efficiency_improvement
- key: transport_trains_efficiency
  step_value: 0.1
  unit: "%"
  position: 5
  slide_key: demand_transport_efficiency_improvement
- key: transport_vehicle_using_hydrogen_efficiency
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_transport_efficiency_improvement
