---
- key: transport_plane_using_kerosene_share
  share_group: transport_aviation
  step_value: 0.1
  unit: "%"
  position: 1
  related_node: transport_plane_using_kerosene_mix
  slide_key: demand_transport_domestic_aviation_technology
- key: transport_plane_using_gasoline_share
  share_group: transport_aviation
  step_value: 0.1
  unit: "%"
  position: 2
  related_node: transport_plane_using_gasoline
  slide_key: demand_transport_domestic_aviation_technology
- key: transport_plane_using_bio_ethanol_share
  share_group: transport_aviation
  step_value: 0.1
  unit: "%"
  position: 3
  related_node: transport_plane_using_bio_ethanol
  slide_key: demand_transport_domestic_aviation_technology
- key: transport_plane_using_hydrogen_share
  share_group: transport_aviation
  step_value: 0.1
  unit: "%"
  position: 4
  related_node: transport_plane_using_hydrogen
  slide_key: demand_transport_domestic_aviation_technology
- key: transport_plane_using_electricity_share
  share_group: transport_aviation
  step_value: 0.1
  unit: "%"
  position: 5
  related_node: transport_plane_using_electricity
  slide_key: demand_transport_domestic_aviation_technology
