---
- key: industry_useful_demand_for_other_ict
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_other_ict
- key: industry_useful_demand_for_other_ict_efficiency
  step_value: 0.1
  unit: "%/year"
  interface_group: efficiency_industry
  position: 2
  slide_key: demand_industry_other_ict
