---
- key: households_heater_combined_network_gas_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_combined_network_gas
  position: 10
  slide_key: demand_households_heating
- key: households_heater_combined_hydrogen_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_combined_hydrogen
  position: 20
  slide_key: demand_households_heating
- key: households_heater_district_heating_ht_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  position: 30
  slide_key: demand_households_heating
- key: households_heater_district_heating_mt_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  position: 40
  slide_key: demand_households_heating
- key: households_heater_district_heating_lt_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  position: 50
  slide_key: demand_households_heating
- key: households_heater_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_air_water_electricity
  position: 60
  slide_key: demand_households_heating
- key: households_heater_heatpump_ground_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_ground_water_electricity
  position: 70
  slide_key: demand_households_heating
- key: households_heater_heatpump_surface_water_water_ts_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_surface_water_water_ts_electricity
  position: 80
  slide_key: demand_households_heating
- key: households_heater_hybrid_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_hybrid_heatpump_air_water_electricity
  position: 90
  slide_key: demand_households_heating
- key: households_heater_hybrid_hydrogen_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_hybrid_hydrogen_heatpump_air_water_electricity
  position: 100
  slide_key: demand_households_heating
- key: households_heater_hybrid_crude_oil_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_crude_oil_hydrogen_heatpump_air_water_electricity
  position: 105
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating  
- key: households_heater_heatpump_pvt_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_pvt_electricity
  position: 120
  slide_key: demand_households_heating
- key: households_heater_wood_pellets_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_wood_pellets
  position: 130
  slide_key: demand_households_heating
- key: households_heater_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_electricity
  position: 140
  slide_key: demand_households_heating
- key: households_heater_network_gas_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_network_gas
  position: 150
  slide_key: demand_households_heating
- key: households_heater_crude_oil_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_crude_oil
  position: 160
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating
- key: households_heater_coal_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_coal
  position: 170
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating

- key: households_water_heater_solar_thermal_share
  step_value: 0.1
  unit: "%"
  interface_group: share_in_hot_water
  related_node: households_water_heater_solar_thermal
  position: 1
  slide_key: demand_households_heating
