---
- key: agriculture_burner_network_gas_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: agriculture_burner_network_gas
  position: 1
  slide_key: demand_agriculture_heat
- key: agriculture_burner_crude_oil_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: agriculture_burner_crude_oil
  position: 2
  slide_key: demand_agriculture_heat
- key: agriculture_burner_wood_pellets_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: agriculture_burner_wood_pellets
  position: 3
  slide_key: demand_agriculture_heat
- key: agriculture_burner_hydrogen_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: agriculture_burner_hydrogen
  position: 4
  slide_key: demand_agriculture_heat
- key: agriculture_heatpump_water_water_electricity_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: agriculture_heatpump_water_water_electricity
  position: 5
  slide_key: demand_agriculture_heat
- key: agriculture_heatpump_water_water_ts_electricity_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: agriculture_heatpump_water_water_ts_electricity
  position: 6
  slide_key: demand_agriculture_heat
- key: agriculture_geothermal_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  position: 7
  slide_key: demand_agriculture_heat
- key: agriculture_final_demand_ht_central_steam_hot_water_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  position: 8
  slide_key: demand_agriculture_heat
- key: agriculture_final_demand_mt_central_steam_hot_water_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  position: 9
  slide_key: demand_agriculture_heat
- key: agriculture_final_demand_local_steam_hot_water_share
  share_group: agri_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  position: 10
  slide_key: demand_agriculture_heat
- key: capacity_of_agriculture_flexibility_p2h_electricity
  step_value: 1.0
  unit: MW
  interface_group: hybrid_heating
  related_node: agriculture_flexibility_p2h_network_gas_electricity
  position: 100
  slide_key: demand_agriculture_heat
