---
- key: transport_ship_using_diesel_mix_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 1
  related_node: transport_ship_using_diesel_mix
  slide_key: demand_transport_domestic_navigation_technology
- key: transport_ship_using_lng_mix_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 2
  related_node: transport_ship_using_lng_mix
  slide_key: demand_transport_domestic_navigation_technology
- key: transport_ship_using_hydrogen_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 3
  related_node: transport_ship_using_hydrogen
  slide_key: demand_transport_domestic_navigation_technology
- key: transport_ship_using_electricity_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 4
  related_node: transport_ship_using_electricity
  slide_key: demand_transport_domestic_navigation_technology
- key: transport_ship_using_ammonia_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 5
  related_node: transport_ship_using_ammonia
  slide_key: demand_transport_domestic_navigation_technology
- key: transport_ship_using_methanol_mix_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 6
  related_node: transport_ship_using_methanol_mix
  slide_key: demand_transport_domestic_navigation_technology
