---
- key: industry_steel_production
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_steel
- key: industry_steel_blastfurnace_bat_consumption_useable_heat_share
  share_group: steel_production
  step_value: 0.1
  unit: "%"
  interface_group: production_technology
  position: 2
  slide_key: demand_industry_steel
- key: industry_steel_blastfurnace_current_consumption_useable_heat_share
  share_group: steel_production
  step_value: 0.1
  unit: "%"
  interface_group: production_technology
  position: 1
  slide_key: demand_industry_steel
- key: industry_steel_hisarna_consumption_useable_heat_share
  share_group: steel_production
  step_value: 0.1
  unit: "%"
  interface_group: production_technology
  position: 3
  slide_key: demand_industry_steel
- key: industry_steel_electricfurnace_electricity_share
  share_group: steel_production
  step_value: 0.1
  unit: "%"
  interface_group: production_technology
  position: 4
  slide_key: demand_industry_steel
- key: energy_steel_hisarna_transformation_coal_woodpellets_share
  step_value: 0.1
  unit: "%"
  interface_group: bio_feedstock
  position: 5
  slide_key: demand_industry_steel
