---
- key: bunkers_ship_using_heavy_fuel_oil_share
  share_group: bunkers_shipping
  step_value: 0.1
  unit: "%"
  position: 1
  related_node: bunkers_ship_using_heavy_fuel_oil
  slide_key: demand_transport_international_navigation_technology
- key: bunkers_ship_using_lng_share
  share_group: bunkers_shipping
  step_value: 0.1
  unit: "%"
  position: 2
  related_node: bunkers_ship_using_lng
  slide_key: demand_transport_international_navigation_technology
