---
- key: industry_useful_demand_for_other_paper
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_other_paper
- key: industry_useful_demand_for_other_paper_electricity_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 2
  slide_key: demand_industry_other_paper
- key: industry_useful_demand_for_other_paper_useable_heat_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 3
  slide_key: demand_industry_other_paper
- key: industry_other_paper_burner_network_gas_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_other_paper_burner_network_gas
  position: 3
  slide_key: demand_industry_other_paper
- key: industry_other_paper_burner_crude_oil_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_other_paper_burner_crude_oil
  position: 4
  slide_key: demand_industry_other_paper
- key: industry_other_paper_burner_wood_pellets_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_other_paper_burner_wood_pellets
  position: 6
  slide_key: demand_industry_other_paper
- key: industry_other_paper_burner_coal_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_other_paper_burner_coal
  position: 5
  slide_key: demand_industry_other_paper
- key: industry_final_demand_for_other_paper_steam_hot_water_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  position: 9
  slide_key: demand_industry_other_paper
- key: industry_other_paper_heater_electricity_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_other_paper_heater_electricity
  position: 8
  slide_key: demand_industry_other_paper
- key: capacity_of_industry_other_paper_flexibility_p2h_electricity
  step_value: 1.0
  unit: MW
  interface_group: hybrid_heating
  related_node: industry_other_paper_flexibility_p2h_network_gas_electricity
  position: 10
  slide_key: demand_industry_other_paper
- key: industry_other_paper_burner_hydrogen_share
  share_group: other_paper_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_other_paper_burner_hydrogen
  position: 7
  slide_key: demand_industry_other_paper
