---
# Interconnector #1
- key: electricity_interconnector_1_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity
  interface_group:
- key: electricity_interconnector_1_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity
  interface_group:
- key: electricity_interconnector_1_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity
  interface_group:

- key: electricity_interconnector_1_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity
  interface_group: co2_emissions
- key: electricity_interconnector_1_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity
  interface_group: co2_emissions

- key: electricity_interconnector_1_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity
  interface_group: costs

# Interconnector #2
- key: electricity_interconnector_2_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_2
  interface_group:
- key: electricity_interconnector_2_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_2
  interface_group:
- key: electricity_interconnector_2_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_2
  interface_group:

- key: electricity_interconnector_2_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_2
  interface_group: co2_emissions
- key: electricity_interconnector_2_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_2
  interface_group: co2_emissions

- key: electricity_interconnector_2_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_2
  interface_group: costs

# Interconnector #3
- key: electricity_interconnector_3_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_3
  interface_group:
- key: electricity_interconnector_3_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_3
  interface_group:
- key: electricity_interconnector_3_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_3
  interface_group:

- key: electricity_interconnector_3_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_3
  interface_group: co2_emissions
- key: electricity_interconnector_3_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_3
  interface_group: co2_emissions

- key: electricity_interconnector_3_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_3
  interface_group: costs

# Interconnector #4
- key: electricity_interconnector_4_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_4
  interface_group:
- key: electricity_interconnector_4_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_4
  interface_group:
- key: electricity_interconnector_4_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_4
  interface_group:

- key: electricity_interconnector_4_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_4
  interface_group: co2_emissions
- key: electricity_interconnector_4_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_4
  interface_group: co2_emissions

- key: electricity_interconnector_4_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_4
  interface_group: costs

# Interconnector #5
- key: electricity_interconnector_5_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_5
  interface_group:
- key: electricity_interconnector_5_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_5
  interface_group:
- key: electricity_interconnector_5_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_5
  interface_group:

- key: electricity_interconnector_5_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_5
  interface_group: co2_emissions
- key: electricity_interconnector_5_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_5
  interface_group: co2_emissions

- key: electricity_interconnector_5_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_5
  interface_group: costs

# Interconnector #6
- key: electricity_interconnector_6_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_6
  interface_group:
- key: electricity_interconnector_6_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_6
  interface_group:
- key: electricity_interconnector_6_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_6
  interface_group:

- key: electricity_interconnector_6_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_6
  interface_group: co2_emissions
- key: electricity_interconnector_6_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_6
  interface_group: co2_emissions

- key: electricity_interconnector_6_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_6
  interface_group: costs

# Interconnector #7
- key: electricity_interconnector_7_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_7
  interface_group:
- key: electricity_interconnector_7_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_7
  interface_group:
- key: electricity_interconnector_7_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_7
  interface_group:

- key: electricity_interconnector_7_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_7
  interface_group: co2_emissions
- key: electricity_interconnector_7_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_7
  interface_group: co2_emissions

- key: electricity_interconnector_7_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_7
  interface_group: costs

# Interconnector #8
- key: electricity_interconnector_8_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_8
  interface_group:
- key: electricity_interconnector_8_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_8
  interface_group:
- key: electricity_interconnector_8_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_8
  interface_group:

- key: electricity_interconnector_8_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_8
  interface_group: co2_emissions
- key: electricity_interconnector_8_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_8
  interface_group: co2_emissions

- key: electricity_interconnector_8_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_8
  interface_group: costs

# Interconnector #9
- key: electricity_interconnector_9_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_9
  interface_group:
- key: electricity_interconnector_9_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_9
  interface_group:
- key: electricity_interconnector_9_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_9
  interface_group:

- key: electricity_interconnector_9_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_9
  interface_group: co2_emissions
- key: electricity_interconnector_9_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_9
  interface_group: co2_emissions

- key: electricity_interconnector_9_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_9
  interface_group: costs

# Interconnector #10
- key: electricity_interconnector_10_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_10
  interface_group:
- key: electricity_interconnector_10_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_10
  interface_group:
- key: electricity_interconnector_10_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_10
  interface_group:

- key: electricity_interconnector_10_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_10
  interface_group: co2_emissions
- key: electricity_interconnector_10_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_10
  interface_group: co2_emissions

- key: electricity_interconnector_10_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_10
  interface_group: costs

# Interconnector #11
- key: electricity_interconnector_11_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_11
  interface_group:
- key: electricity_interconnector_11_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_11
  interface_group:
- key: electricity_interconnector_11_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_11
  interface_group:

- key: electricity_interconnector_11_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_11
  interface_group: co2_emissions
- key: electricity_interconnector_11_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_11
  interface_group: co2_emissions

- key: electricity_interconnector_11_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_11
  interface_group: costs

# Interconnector #12
- key: electricity_interconnector_12_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity_12
  interface_group:
- key: electricity_interconnector_12_import_availability
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity_12
  interface_group:
- key: electricity_interconnector_12_export_availability
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity_12
  interface_group:

- key: electricity_interconnector_12_co2_emissions_present
  step_value: 1.0
  unit: g/kWh
  position: 4
  slide_key: flexibility_electricity_import_export_interconnectivity_12
  interface_group: co2_emissions
- key: electricity_interconnector_12_co2_emissions_future
  step_value: 1.0
  unit: g/kWh
  position: 5
  slide_key: flexibility_electricity_import_export_interconnectivity_12
  interface_group: co2_emissions

- key: electricity_interconnector_12_marginal_costs
  step_value: 0.1
  unit: "€/MWh"
  position: 6
  slide_key: flexibility_electricity_import_export_interconnectivity_12
  interface_group: costs
