---
- key: capacity_of_energy_heat_flexibility_p2h_boiler_electricity
  step_value: 0.1
  unit: MW
  interface_group: capacity
  related_node: energy_heat_flexibility_p2h_boiler_ht_electricity
  position: 1
  slide_key: flexibility_flexibility_power_to_heat_for_district_heating
- key: capacity_of_energy_heat_flexibility_p2h_heatpump_electricity
  step_value: 0.1
  unit: MW
  interface_group: capacity
  related_node: energy_heat_flexibility_p2h_heatpump_ht_electricity
  position: 2
  slide_key: flexibility_flexibility_power_to_heat_for_district_heating
- key: wtp_of_energy_heat_flexibility_p2h_boiler_electricity
  step_value: 0.1
  unit: "€/MWh"
  interface_group: willingness_to_pay
  related_node: energy_heat_flexibility_p2h_boiler_ht_electricity
  position: 3
  slide_key: flexibility_flexibility_power_to_heat_for_district_heating
- key: wtp_of_energy_heat_flexibility_p2h_heatpump_electricity
  step_value: 0.1
  unit: "€/MWh"
  interface_group: willingness_to_pay
  related_node: energy_heat_flexibility_p2h_heatpump_ht_electricity
  position: 4
  slide_key: flexibility_flexibility_power_to_heat_for_district_heating
- key: temperature_cutoff_of_energy_flexibility_p2h
  step_value: 0.1
  unit: "degC"
  interface_group: thermostat
  related_node:
  position: 5
  slide_key: flexibility_flexibility_power_to_heat_for_district_heating
