---
- key: capacity_of_flexibility_p2l_electricity
  step_value: 1.0
  unit: MW
  related_converter: bunkers_kerosene_production_p2l
  position: 1
  slide_key: flexibility_flexibility_power_to_kerosene
- key: flexibility_p2l_direct_air_capture
  share_group: carbon_source_p2l
  step_value: 0.1
  unit: "%"
  interface_group: carbon_source_p2l
  related_converter: bunkers_p2l_direct_air_capture
  position: 4
  slide_key: flexibility_flexibility_power_to_kerosene
- key: flexibility_p2l_point_source_co
  share_group: carbon_source_p2l
  step_value: 0.1
  unit: "%"
  interface_group: carbon_source_p2l
  related_converter: bunkers_p2l_point_source_CO
  position: 2
  slide_key: flexibility_flexibility_power_to_kerosene
- key: flexibility_p2l_point_source_co2
  share_group: carbon_source_p2l
  step_value: 0.1
  unit: "%"
  interface_group: carbon_source_p2l
  related_converter: bunkers_p2l_point_source_CO2
  position: 3
  slide_key: flexibility_flexibility_power_to_kerosene
- key: flexibility_p2l_co2_reduction_industry
  share_group: co2_reduction_p2l
  step_value: 0.1
  unit: "%"
  interface_group: co2_reduction_p2l
  position: 5
  slide_key: flexibility_flexibility_power_to_kerosene
- key: flexibility_p2l_co2_reduction_bunkers
  share_group: co2_reduction_p2l
  step_value: 0.1
  unit: "%"
  interface_group: co2_reduction_p2l
  position: 6
  slide_key: flexibility_flexibility_power_to_kerosene
