---
- key: households_flexibility_space_heating_cop_cutoff
  step_value: 0.1
  unit: "#"
  interface_group: flexibility_cop
  position: 1
  slide_key: flexibility_flexibility_demand_response_hhp
- key: households_flexibility_water_heating_cop_cutoff
  step_value: 0.1
  unit: "#"
  interface_group: flexibility_cop
  position: 2
  slide_key: flexibility_flexibility_demand_response_hhp
- key: households_flexibility_consumer_gas_price
  step_value: 0.1
  unit: ct/m3
  interface_group: consumer_price
  position: 3
  slide_key: flexibility_flexibility_demand_response_hhp
- key: households_flexibility_consumer_electricity_price
  step_value: 0.1
  unit: ct/kWh
  interface_group: consumer_price
  position: 4
  slide_key: flexibility_flexibility_demand_response_hhp
