---
- key: capacity_of_energy_chp_local_engine_biogas
  step_value: 1.0
  unit: MW
  related_node: energy_chp_local_engine_ht_biogas
  position: 2
  slide_key: supply_electricity_renewable_biomass_plants
- key: capacity_of_energy_chp_local_wood_pellets
  step_value: 0.1
  unit: MW
  related_node: energy_chp_local_ht_wood_pellets
  position: 1
  slide_key: supply_electricity_renewable_biomass_plants
