---
- key: volume_of_imported_heat
  step_value: 0.1
  unit: PJ
  interface_group: residual_heat
  position: 4
  slide_key: supply_heat_sources
- key: co2_emissions_of_imported_heat
  step_value: 0.1
  unit: kg/GJ
  interface_group: residual_heat
  position: 5
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_well_geothermal
  step_value: 1.0
  unit: MW
  interface_group: non_dispatchable_heat
  related_node: energy_heat_well_geothermal
  position: 1
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_solar_thermal
  step_value: 1.0
  unit: MW
  interface_group: non_dispatchable_heat
  related_node: energy_heat_solar_thermal
  position: 2
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_heatpump_water_water_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_heatpump_water_water_electricity
  position: 6
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_boiler_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_boiler_electricity
  position: 7
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_burner_network_gas
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_burner_network_gas
  position: 8
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_burner_hydrogen
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_burner_hydrogen
  position: 9
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_burner_wood_pellets
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_burner_wood_pellets
  position: 10
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_burner_waste_mix
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_burner_waste_mix
  position: 11
  slide_key: supply_heat_sources
- key: capacity_of_energy_heat_burner_crude_oil
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_node: energy_heat_burner_crude_oil
  position: 12
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: supply_heat_sources
- key: share_of_industry_chemicals_other_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_sources
- key: share_of_industry_chemicals_fertilizers_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_sources
- key: share_of_industry_chemicals_refineries_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_sources
- key: share_of_industry_other_ict_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_sources
