---
- key: capacity_of_energy_power_wind_turbine_inland
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_power_wind_turbine_inland
  position: 1
  slide_key: supply_electricity_renewable_wind_turbines
- key: capacity_of_energy_power_wind_turbine_coastal
  step_value: 1.0
  unit: MW
  related_node: energy_power_wind_turbine_coastal
  position: 2
  dependent_on: has_coastline
  slide_key: supply_electricity_renewable_wind_turbines
- key: capacity_of_energy_power_wind_turbine_offshore
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_power_wind_turbine_offshore
  position: 3
  slide_key: supply_electricity_renewable_wind_turbines
- key: capacity_of_energy_power_hybrid_wind_turbine_offshore
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_power_hybrid_wind_turbine_offshore
  position: 4
  slide_key: supply_electricity_renewable_wind_turbines
- key: capacity_of_energy_battery_wind_turbine_inland
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_battery_wind_turbine_inland
  position: 5
  slide_key: supply_electricity_renewable_wind_turbines
