---
- key: capacity_of_energy_power_supercritical_waste_mix
  step_value: 1.0
  unit: MW
  related_node: energy_power_supercritical_waste_mix
  position: 1
  slide_key: supply_electricity_renewable_waste_power
- key: capacity_of_energy_chp_supercritical_waste_mix
  step_value: 1.0
  unit: MW
  related_node: energy_chp_supercritical_ht_waste_mix
  position: 2
  slide_key: supply_electricity_renewable_waste_power
