---
- key: capacity_of_industry_chp_combined_cycle_gas_power_fuelmix
  step_value: 1.0
  unit: MW
  related_node: industry_chp_combined_cycle_gas_power_fuelmix
  position: 1
  interface_group: industry_chps
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_chp_turbine_gas_power_fuelmix
  step_value: 1.0
  unit: MW
  related_node: industry_chp_turbine_gas_power_fuelmix
  position: 2
  interface_group: industry_chps
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_chp_engine_gas_power_fuelmix
  step_value: 1.0
  unit: MW
  related_node: industry_chp_engine_gas_power_fuelmix
  position: 3
  interface_group: industry_chps
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_chp_ultra_supercritical_coal
  step_value: 1.0
  unit: MW
  related_node: industry_chp_ultra_supercritical_coal
  position: 4
  interface_group: industry_chps
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_chp_wood_pellets
  step_value: 1.0
  unit: MW
  related_node: industry_chp_wood_pellets
  position: 5
  interface_group: industry_chps
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_heat_burner_coal
  step_value: 1.0
  unit: MW
  related_node: industry_heat_burner_coal
  position: 6
  interface_group: industry_heaters
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_heat_burner_crude_oil
  step_value: 1.0
  unit: MW
  related_node: industry_heat_burner_crude_oil
  position: 7
  interface_group: industry_heaters
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_heat_burner_lignite
  step_value: 1.0
  unit: MW
  related_node: industry_heat_burner_lignite
  position: 8
  interface_group: industry_heaters
  dependent_on: has_lignite
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_heat_well_geothermal
  step_value: 1.0
  unit: MW
  related_node: industry_heat_well_geothermal
  position: 9
  interface_group: industry_heaters
  slide_key: supply_heat_network_industry
- key: capacity_of_industry_heat_burner_hydrogen
  step_value: 1.0
  unit: MW
  related_node: industry_heat_burner_hydrogen
  position: 10
  interface_group: industry_heaters
  slide_key: supply_heat_network_industry

