ete_url: <%= ENV.fetch('ETE_URL', 'https://engine.energytransitionmodel.com') %>
converter_detail_url: https://engine.energytransitionmodel.com/converters
esdl_ete_url: https://esdl.energytransitionmodel.com/api/v1/
gquery_detail_url: https://engine.energytransitionmodel.com/data/latest/gqueries/
live_server: production
multi_year_charts_url: https://collections.energytransitionmodel.com
collections_url: https://collections.energytransitionmodel.com          # putting both in for now for safety
partners_url: https://energytransitionmodel.com

identity:
  client_uri: <%= ENV.fetch('IDENTITY_CLIENT_URI', 'https://energytransitionmodel.com') %>
  issuer: <%= ENV.fetch('IDP_URL', 'https://my.energytransitionmodel.com') %>
  resource_uri: <%= ENV.fetch('ETE_URL', 'https://engine.energytransitionmodel.com') %>
